### ISSUE TITLE
Unable to run complete document through the pipeline

### ISSUE THREAD

**Issue by buntys2010** [deepdoctection/deepdoctection#126]
**Bug** 💥
When i run pipeline [here](https://github.com/deepdoctection/notebooks/blob/main/Get_Started.ipynb) it runs on first page of the document instead of all the pages.

```
doc = iter(df)
page = next(doc) 
```
Is there a way to run all the pages in the document?

**Expected behavior**  🧮 
Run all the pages in the document instead of first page.

**Comment by JaMe76** [comment]
To process all pages simply run a for loop over your dataflow.

**Comment by buntys2010** [comment]
Can you provide a simple code example please?

**Comment by buntys2010** [comment]
Thanks this has solved my issue, thanks for your help.

**Comment by Matheus-Garbelini** [comment]
@JaMe76 is there a way to run multiple pages via batching?

**Comment by JaMe76** [comment]
@Matheus-Garbelini  Unfortunately not yet: Inference runs are still sequential only and allowing image batch processing will require re-design of the pipeline component in conjunction with the predictor. 

There is [this discussion](https://github.com/deepdoctection/deepdoctection/discussions/240) and [this issue](https://github.com/deepdoctection/deepdoctection/issues/123)  with ideas about how things could be speed up. 

But there has been not much work towards this direction...

**Comment by Matheus-Garbelini** [comment]
Thanks @JaMe76. For now I'm using YoloV8x for document segmentation detection: https://huggingface.co/DILHTWD/documentlayoutsegmentation_YOLOv8_ondoclaynet
The scores on DocLayNet, IBM are a bit unbelievable, but I wonder if such weights can help this project:
Metrics:
Precision: 0.98
Recall: 0.97
F1: 0.97
mAP50: 0.99
mAP50-95: 0.95

Regards.

**Comment by JaMe76** [comment]
@Matheus-Garbelini : 😳 … this must be a typo.  I was just checking the doclaynet paper. They reported a mAP50-0.95:0.76, it is very unlikely that a v8 will give such a boost. 

Lookin at the confusion matrix, it seems they grouped some labels as there are only 5 compared to 11 in the original annotations. This will give you a higher mAP, but even then this does not explain their results. 

Anyway, this could help the project. The model isn’t huge, definitely something that could qualify for the general purpose. Thanks for pointing to the weights!
