### ISSUE TITLE
Dataset tutorial is not visible

### ISSUE THREAD

**Issue by koszilard** [deepdoctection/deepdoctection#127]
**Bug** 💥
Dataset tutorial is not visible in Chrome or Edge browsers. https://[deepdoctection](https://deepdoctection.readthedocs.io/en/latest/tutorials/datasets.html).readthedocs.io/en/latest/tutorials/datasets.html

**Expected behavior**  🧮 
Tutorial is visible

**Screenshots** 🖼
![image](https://user-images.githubusercontent.com/6463260/224636580-ab32b88f-3fa9-4d51-bd02-7ec8f81bb9fb.png)

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Windows

**Additional context** 🧬

**Comment by JaMe76** [comment]
Where is the url you mentioned coming from ?

Can you check, if https://deepdoctection.readthedocs.io/en/latest/tutorials/datasets/ is visible from your browser ? This url comes from following the link from docs menu toolbar.

**Comment by koszilard** [comment]
The one you just shared works, I got the one from the discussions section. 
Thanks!
