### ISSUE TITLE
Issues installing on M1 Mac

### ISSUE THREAD

**Issue by jhoetter** [deepdoctection/deepdoctection#130]
**Bug** 💥
Even after an hour of waiting, it seems like my installation doesn't get past
```
Building wheels for collected packages: opencv-python, pycocotools
Building wheel for opencv-python (pyproject.toml) ... \
```

**Expected behavior**  🧮 
Installing opencv-python standalone worked, so confused why the installation is blocked

**Screenshots** 🖼
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62521561/226633185-18eb4ea0-22ce-4c11-81ff-ae52fce609d6.png">

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: MacOS Ventura 13.2.1

**Additional context** 🧬
Sorry, knowing this most likely is a fault of my own and I'll try to fix it myself, but maybe this is an issue that happens to someone else as well - so I thought sharing it helps.

**Comment by JaMe76** [comment]
Thanks for your comment.

The installation with extras has quite a few dependencies and there had been a couple issues when installing in a conda environment before. 

Good to see that the problem has been resolved.
