### ISSUE TITLE
Cannot load custom dataset

### ISSUE THREAD

**Issue by SandPhoenixX517** [deepdoctection/deepdoctection#133]
**Bug** 💥
I am trying to fine-tune deepdoctection on a custom dataset that I have. After putting the dataset in the right format and folder, I am trying to load it from the code so that I can use it to fine-tune the model.
However, I am not finding the right import statements within the documentation.
After following this https://deepdoctection.readthedocs.io/en/latest/tutorials/datasets/
I am facing issues with the <strong> DatasetCategories </strong> section where I am getting the error "NameError: name 'object_types_registry' is not defined".
Then I also cannot find my custom dataset in the registry which I assume it is also dued to the previous error.

**Expected behavior**  🧮 
Find the custom dataset in the registry and be able to load it.
**Screenshots** 🖼
![image](https://user-images.githubusercontent.com/60070961/228855954-93c58c35-23ca-4b04-8979-e3746107bb3d.png)

I would appreciate any help :)

**Comment by JaMe76** [comment]
Hi,

This is a Copy-Paste from the sample, isn’t it?

Not defined means that the object registry is not properly imported:

try:

@dd.object_type_registry….

**Comment by SandPhoenixX517** [comment]
Hello,

Thanks for responding.
It is indeed a copy paste... I was just trying it out for now to see whether I should continue or not.
I will try that out and tell you if works.
