### ISSUE TITLE
How to detect table structure only

### ISSUE THREAD

**Issue by similang** [deepdoctection/deepdoctection#140]
Hi, 

Is there a way to detect table structure only?

Thanks.

**Comment by JaMe76** [comment]
Hi, 

can you elaborate on the problem a little bit? What of the following is the pipeline supposed to do?

- Table detection only (ignoring any other layout structure) ?
- Table structure recognition ?
- Getting text from cells only (e.g. ignoring text outside the table) as csv, HTML ?

Every step requires a separate component so the solution depends heavily at what you are looking for.

**Comment by similang** [comment]
Table structure recognition only, i.e.: I have detected the table and with some preprocessing. 
I am looking for a way to get the rows and columns only now.

**Comment by similang** [comment]
Hi any comment on the above? @JaMe76
