### ISSUE TITLE
Not able to build pytorch-cpu docker image.

### ISSUE THREAD

**Issue by ryanmcdonough** [deepdoctection/deepdoctection#146]
**Bug** 💥
python3 - pip install fails

`=> ERROR [6/6] RUN python3 -m pip install --no-cache-dir ".[source-pt]"                                  2.3s 
------                                                                                                         
 > [6/6] RUN python3 -m pip install --no-cache-dir ".[source-pt]":                                             
#10 1.803 ERROR: Directory '.[source-pt]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.   
#10 2.162 WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.                     
#10 2.162 You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.`

**Expected behavior**  🧮 
It to complete the install process

**Screenshots** 🖼
If possible, please add a screenshot of the error message, if possible

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Mac OS

**Additional context** 🧬
`docker build .
[+] Building 459.7s (10/10) FINISHED                                                                           
 => [internal] load build definition from Dockerfile                                                      0.0s
 => => transferring dockerfile: 626B                                                                      0.0s
 => [internal] load .dockerignore                                                                         0.0s
 => => transferring context: 2B                                                                           0.0s
 => [internal] load metadata for docker.io/library/python:3.8-slim                                        2.8s
 => [internal] load build context                                                                         0.0s
 => => transferring context: 621B                                                                         0.0s
 => [1/6] FROM docker.io/library/python:3.8-slim@sha256:f4efb39d02df8cdc44485a0956ea62e63aab6bf2a1dcfb1  14.6s
 => => resolve docker.io/library/python:3.8-slim@sha256:f4efb39d02df8cdc44485a0956ea62e63aab6bf2a1dcfb12  0.0s
 => => sha256:92689d355058ec11621b8ad082b5e9191143aac0019051aaff702ede49ed2502 1.37kB / 1.37kB            0.0s
 => => sha256:015fc0fe8ec77be8ec4a6920c64afde4933588545e34ab8f33eb597a48effe9a 6.93kB / 6.93kB            0.0s
 => => sha256:0060f14183eaba69bdd5397206214f30ff3e1d3609f5c29f01b59bbf2a2d9217 10.89MB / 10.89MB         13.5s
 => => sha256:b3e690cd2eee43ccdcf9fd4daae3531ee4222e82b2e0d784182a2012a40ba003 244B / 244B                1.0s
 => => sha256:a6be8f6cd009c70451a108501e52f757790f72741f6551b5d983677d75d407b1 3.20MB / 3.20MB            6.7s
 => => sha256:f4efb39d02df8cdc44485a0956ea62e63aab6bf2a1dcfb12fb5710bf95583e72 1.86kB / 1.86kB            0.0s
 => => extracting sha256:0060f14183eaba69bdd5397206214f30ff3e1d3609f5c29f01b59bbf2a2d9217                 0.5s
 => => extracting sha256:b3e690cd2eee43ccdcf9fd4daae3531ee4222e82b2e0d784182a2012a40ba003                 0.0s
 => => extracting sha256:a6be8f6cd009c70451a108501e52f757790f72741f6551b5d983677d75d407b1                 0.3s
 => [2/6] WORKDIR /home/repo                                                                              0.1s
 => [3/6] COPY . .                                                                                        0.0s
 => [4/6] RUN apt-get update &&     apt install -y git                    poppler-utils                 251.4s
 => [5/6] RUN python3 -m pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl  188.2s
 => ERROR [6/6] RUN python3 -m pip install --no-cache-dir ".[source-pt]"                                  2.3s 
------                                                                                                         
 > [6/6] RUN python3 -m pip install --no-cache-dir ".[source-pt]":                                             
#10 1.803 ERROR: Directory '.[source-pt]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.   
#10 2.162 WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.                     
#10 2.162 You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command. 
------
executor failed running [/bin/sh -c python3 -m pip install --no-cache-dir ".[source-pt]"]: exit code: 1
ryan@Ryans-MacBook-Pro pytorch-cpu % docker build .
[+] Building 4.6s (10/10) FINISHED                                                                             
 => [internal] load build definition from Dockerfile                                                      0.0s
 => => transferring dockerfile: 120B                                                                      0.0s
 => [internal] load .dockerignore                                                                         0.0s
 => => transferring context: 2B                                                                           0.0s
 => [internal] load metadata for docker.io/library/python:3.8-slim                                        2.3s
 => [1/6] FROM docker.io/library/python:3.8-slim@sha256:f4efb39d02df8cdc44485a0956ea62e63aab6bf2a1dcfb12  0.0s
 => [internal] load build context                                                                         0.0s
 => => transferring context: 115B                                                                         0.0s
 => CACHED [2/6] WORKDIR /home/repo                                                                       0.0s
 => CACHED [3/6] COPY . .                                                                                 0.0s
 => CACHED [4/6] RUN apt-get update &&     apt install -y git                    poppler-utils            0.0s
 => CACHED [5/6] RUN python3 -m pip install --no-cache-dir --extra-index-url https://download.pytorch.or  0.0s
 => ERROR [6/6] RUN python3 -m pip install --no-cache-dir ".[source-pt]"                                  2.1s
------                                                                                                         
 > [6/6] RUN python3 -m pip install --no-cache-dir ".[source-pt]":                                             
#10 1.682 ERROR: Directory '.[source-pt]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.   
#10 2.005 WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
#10 2.005 You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
------`

**Comment by JaMe76** [comment]
This looks similar to #129 .

Did you build like that from the repo base dir ?

```
docker build -t dd:<your-tag> -f docker/pytorch-cpu-jupyter/Dockerfile .
``` 

There is a short README under

https://github.com/deepdoctection/deepdoctection/tree/master/docker/pytorch-cpu-jupyter .

If this works, I’ll be adding the instruction to the pytorch-cpu directory as well.

**Comment by ryanmcdonough** [comment]
So I'd built from the pytorch-cpu folder root, using `docker build .`

Yes, doing: `docker build -t dd:doc -f docker/pytorch-cpu/Dockerfile .   ` from the root of the folder worked perfectly.
