### ISSUE TITLE
Where is the 'item' config dir???

### ISSUE THREAD

**Issue by hongge831** [deepdoctection/deepdoctection#152]
**Bug** 💥
Please describe the error you encoutered

**Expected behavior**  🧮 
Describe what you would have expected

**Screenshots** 🖼
If possible, please add a screenshot of the error message, if possible

**Desktop (please complete the following information, if any other than the one in the install requirements):**

**Additional context** 🧬
If necessary add some context related to the problem

**Comment by JaMe76** [comment]
Depends on whether you use TF or PT.

```python
import deepdoctection as dd

print(dd.ModelCatalog.get_full_path_configs(cfg.CONFIG.TPITEM))
print(dd.ModelCatalog.get_full_path_configs(cfg.CONFIG.D2ITEM))
```

**Comment by hongge831** [comment]
Thanks for your reply，and one more question: In the Huggingface demo, which ocr setting do you use? the OCR performance of mine is much worse than the hugginface demo? Can you help me to figure it out?

**Comment by hongge831** [comment]
And the layout performance is also much worse, would you mind telling me how to fix the performance degration ?

**Comment by hongge831** [comment]
Thanks for your detailed reply,  and I have another question, I notice that the layout model should be able to detect layout type of  'list' and 'figure', but, In the released code base it can hardly detect these two type. And the question is how can I improve the model's capbility or how can I intergrate other sota layout model into your code?( e.g. how can I intergrate the microsoft' layoutLm3_on_Publaynet model into the current codebase )

looking forward to your reply again!

**Comment by hongge831** [comment]
OK Thanks I will keep following.

**Comment by JaMe76** [comment]
Docs and notebook repo have been updated:

https://deepdoctection.readthedocs.io/en/latest/tutorials/running_pre_trained_models_from_other_libraries/

https://github.com/deepdoctection/notebooks/blob/main/Running_pre_trained_models_from_other_libraries.ipynb

**Comment by yashsandansing** [comment]
@JaMe76 were the links for pre-training from other libraries removed? Both links are invalid

**Comment by JaMe76** [comment]
Notebook has been changed and docs have moved:

https://github.com/deepdoctection/notebooks/blob/main/Running_pre_trained_models_from_third_party_libraries.ipynb

https://deepdoctection.readthedocs.io/en/latest/tutorials/running_pre_trained_models_from_third_party_libraries_notebook/

**Comment by yashsandansing** [comment]
@JaMe76 Thanks. But what if I need to add a model that doesn't belong to layoutparser, say `DiT`?  Could you please tell me what should I replace the D2FrcnnDetector with?

**Comment by JaMe76** [comment]
Not supported out of the box.

You will have to write a `DiTDetector`, akin to `HFDetrDerivedDetector`.
