### ISSUE TITLE
`MappingContextManager` error due to error in text ordering

### ISSUE THREAD

**Issue by JaMe76** [deepdoctection/deepdoctection#168]
**Bug** 💥

The following does not break the code but currently produces a lot of `MappingContextManager` warnings.

1.) Cells in Tables get selected multiple times in text ordering because their `annotation_id`s are saved under the same `relationship` key as `ImageAnnotation` of type word. However, cells should not even be ordered and the ordering doesn't apply at any stage.

2.) Currently text blocks that are not part of narrative text will be ordered. However, they have to be ignored.

**Expected behavior**  🧮 
Less warnings and error logs.

**Screenshots** 🖼
If possible, please add a screenshot of the error message, if possible

**Desktop (please complete the following information, if any other than the one in the install requirements):**

**Additional context** 🧬
If necessary add some context related to the problem

**Comment by frivas-at-navteca** [comment]
Would this [Screenshot](https://www.dropbox.com/s/848d7krqzutp2o2/Screenshot%202023-07-06%20at%2011.08.54.png?dl=0) be a good one? 

Thank you very much!
Have a great day
