### ISSUE TITLE
attributeError: module 'deepdoctection.train' has no attribute 'train_d2_faster_rcnn'

### ISSUE THREAD

**Issue by himasai9711** [deepdoctection/deepdoctection#170]
**Bug** 💥
I have been tying to train the model but im getting `attributeError: module 'deepdoctection.train' has no attribute `'train_d2_faster_rcnn'`` and this is my peace of code im using 
```
dd.train_d2_faster_rcnn(path_config,
                        merge,
                        path_weights,
                        ["SOLVER.IMS_PER_BATCH=2", "SOLVER.MAX_ITER=240000", "SOLVER.CHECKPOINT_PERIOD=4000",
                         "SOLVER.STEPS=(160000, 190000)", "TEST.EVAL_PERIOD=4000", 
                         "MODEL.BACKBONE.FREEZE_AT=0",
                         "WANDB.USE_WANDB=True", "WANDB.PROJECT=layout_detection"],
                         "/dbfs/mnt/ocr/",
                         None,
                         merge,
                         None,
                         None,
                         coco,
                         "ImageLayoutService")
```
i saw github python file i can see that function and in the tutorials also you guys are saying same method to use for train

**Comment by JaMe76** [comment]
Looks like one of PyTorch, Detectron2 is not properly installed.

Can you check

```python
import deepdoctection as dd

print(dd.pytorch_available())
print(dd.detectron2_available())
```

Both need to return `True`.

**Comment by himasai9711** [comment]
I ran the above code `print(dd.pytorch_available())` this gives me error 
`AttributeError: module deepdoctection has no attribute pytorch_available`

and the other detectron2 giving me false i have tried many ways to install it i couldnt actually 
and for above I did
```
import deepdoctection as dd
 dir(dd)
```

i couldnt find `pytorch_available()` but i can see `train_d2_faster_rcnn()`


please let me know how to solve this

**Comment by JaMe76** [comment]
Difficult to help without any info on OS, Python version, CUDA, etc. 

Detectron2 is not supported on Windows. It can be installed but it is difficult. Other option is using Docker.

**Comment by himasai9711** [comment]
I'm running on azure databricks

**Comment by himasai9711** [comment]
I'm running under Databricks, python version of 3.9 and the model you guys have in huggingface and can i get that pretrained model ? To test on my few document AI.
