### ISSUE TITLE
`RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage`

### ISSUE THREAD

**Issue by DiTo97** [deepdoctection/deepdoctection#175]
**Bug** 💥
The bug occurs any time I try to instantiate the analyzer on Google Colab regardless of the runtime type.

**Additional context** 🧬
The following cells help reproduce the notebook:

```bash
git clone https://github.com/deepdoctection/deepdoctection.git

python -m pip install --upgrade pip

cd deepdoctection
python -m pip install ".[source-pt]"
cd ..

python -m pip install tf2onnx
python -m pip install tensorflow-addons
python -m pip install packaging==21.3
```

```python
import deepdoctection


config = [
    "OCR.USE_TESSERACT=False",
    "OCR.USE_DOCTR=True",
    "OCR.WEIGHTS.DOCTR_WORD.PT=doctr/db_resnet50/pt/db_resnet50-ac60cadc.pt",
    "OCR.WEIGHTS.DOCTR_RECOGNITION.PT=doctr/crnn_vgg16_bn/pt/crnn_vgg16_bn-9762b0b0.pt"
]

analyzer = deepdoctection.get_dd_analyzer(config_overwrite=config)
```

**Comment by JaMe76** [comment]
Thanks for reporting. I don’t know a solution yet, but 

1. Is Tensorflow addons and tfonnx necessary and installation fails otherwise? It shouldn’t, because the Pytorch framework is used.
2. Does it work with `USE_OCR=False`?
3. If you set  `OCR.USE_DOCTR=True` you basically don’t need to specify the next two config settings as they are already in the yaml. Have the models been downloaded? They should be cached at

```
ModelCatalog.get_full_path_weights(“doctr/db_resnet50/pt/db_resnet50-ac60cadc.pt”)
```

**Comment by DiTo97** [comment]
Hi @JaMe76,

I will reply between points:

> 1. Is Tensorflow addons and tfonnx necessary and installation fails otherwise? It shouldn’t, because the Pytorch framework is used.

They should not be necessary, but they are. I suspect that since Google Colab's venv already has TensorFlow installed, functions such as [`tf_available`](https://github.com/deepdoctection/deepdoctection/blob/4da7668f95ae0cbfe767d2dded9651a03b23dedf/deepdoctection/utils/file_utils.py#L39) are triggered somewhere requesting the installation of those extra libraries.

> 2. Does it work with `USE_OCR=False`?

No. The same error is raised yet again.

> 3. If you set  `OCR.USE_DOCTR=True` you basically don’t need to specify the next two config settings as they are already in the yaml. Have the models been downloaded? They should be cached at
> 
> ```
> ModelCatalog.get_full_path_weights(“doctr/db_resnet50/pt/db_resnet50-ac60cadc.pt”)
> ```

Yes. The models have been cached to the correct file location.

**Comment by JaMe76** [comment]
Thanks for the update.

While I have managed to get it work in some environment where TF and PT is installed, I would not really rely on. I had an assertion before that blocked the installation when both libraries are installed but removed it after a request. I. think at least putting a warning would be sensible.

Thanks again for your update.
