### ISSUE TITLE
AttributeError: LEFT

### ISSUE THREAD

**Issue by soumilbaldota** [deepdoctection/deepdoctection#176]
**Bug** 💥
Please describe the error you encoutered

AttributeError                            Traceback (most recent call last)
[<ipython-input-3-2abe2b1c4387>](https://localhost:8080/#) in <cell line: 2>()
      1 config_overwrite = ["PT.LAYOUT.WEIGHTS=microsoft/table-transformer-detection/pytorch_model.bin"]
----> 2 analyzer = dd.get_dd_analyzer(config_overwrite=config_overwrite)

4 frames
[/usr/local/lib/python3.10/dist-packages/deepdoctection/utils/metacfg.py](https://localhost:8080/#) in __getattr__(self, name)
     44         """
     45         if self._freezed:
---> 46             raise AttributeError(name)
     47         if name.startswith("_"):
     48             # Do not mess with internals. Otherwise, copy/pickle will fail

AttributeError: LEFT

**Expected behavior**  🧮 
Describe what you would have expected: Code should run properly
`config_overwrite = ["PT.LAYOUT.WEIGHTS=microsoft/table-transformer-detection/pytorch_model.bin"]
analyzer = dd.get_dd_analyzer(config_overwrite=config_overwrite)
`

**Screenshots** 🖼
If possible, please add a screenshot of the error message, if possible
![image](https://github.com/deepdoctection/deepdoctection/assets/71919921/25850a85-30b2-4351-89a6-857fe8cffca1)

**Desktop (please complete the following information, if any other than the one in the install requirements):**
Google Colab
**Additional context** 🧬
If necessary add some context related to the problem
https://github.com/deepdoctection/deepdoctection/blame/4da7668f95ae0cbfe767d2dded9651a03b23dedf/configs/conf_dd_one.yaml#L21

Is this quote supposed to be here?

**Comment by JaMe76** [comment]
Thanks for reporting. 

Yes, the quote shouldn’t be there.

**Comment by abhijith63** [comment]
@JaMe76 Is there any temporary fix to this issue that I can do to make it work? I also faced the same error.

**Comment by JaMe76** [comment]
Config file will be saved at:

```python
get_configs_dir_path() / "dd/conf_dd_one.yaml"
```

where you can remove the quote.

When calling the analyzer factory make sure that you change the default value of `reset_config_file`, i.e.

```python
get_dd_analyzer(reset_config_file= False)
```

The default value `reset_config_file` will be changed in the future, but for now this will work for a temporary fix.
