### ISSUE TITLE
short_edge_length must be two values using 'range' sample style. Got (640, 672, 704, 736, 768, 800)!

### ISSUE THREAD

**Issue by himasai9711** [deepdoctection/deepdoctection#179]
hi, im facing this error while traing the model for layout parsing, this is the error im facing

<img width="1013" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/acc2c99e-0fc0-4682-8eb3-51c23fbc8b51">

**Comment by himasai9711** [comment]
Im using this highlighted model file im using for my layout training:

<img width="1013" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/d4ef9de6-1012-4507-93fb-8fe53764a04e">

this is the corresponding config file im using:

<img width="1013" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/c657e315-aa31-407c-9fe4-8d2f9e27281e">

**Comment by JaMe76** [comment]
These are no weights from deepdoctection.

You need to make sure that cfg.INPUT.MIN_SIZE_TRAIN is defined as in
 CASCADE_RCNN_R_50_FPN_GN.yaml.

**Comment by himasai9711** [comment]
In documentation you guys gave this link from download model file and config
