### ISSUE TITLE
AssertionError: Checkpoint /root/.cache/deepdoctection/weights/test2 not found!

### ISSUE THREAD

**Issue by himasai9711** [deepdoctection/deepdoctection#182]
<img width="1013" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/c7136357-ba63-4421-a35e-7c5ae3b4694b">
any way to change the check point path?

my registered model:

<img width="1013" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/8529f2c4-cbbb-4f8c-a4f3-67958810f7f5">

**Comment by JaMe76** [comment]
Name in profile does not point to registered model. You must use the path that defines the key in the registry.

**Comment by himasai9711** [comment]
if i use registered model, it is setting different cofig file but that config path is not found ,that error i got
