### ISSUE TITLE
while training the training process is struck at iteration 0

### ISSUE THREAD

**Issue by himasai9711** [deepdoctection/deepdoctection#185]
<img width="1456" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/051ee507-1eea-4aa1-9f4c-6175735d9c83">

I ran the training for 2hrs and its struck at that iteration for a while.

<img width="710" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/56d7cb36-55bf-4899-8853-f5f3e55e7d8e">

the above image shows my gpu information and the dataset im using are publaynet and doclaynet and this is the number of datapoints for split

<img width="840" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/54b8eb5d-d0d5-44f4-ab5d-d4c278023753">

This is my GPU summary

<img width="502" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/b3baccb6-2ef0-439e-8e1d-3dc41220cda8">

this is the GPU usage from Wandb as its changing:

<img width="1680" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/41705c72-88db-47a5-8401-f2d08bbbffed">

**Comment by JaMe76** [comment]
Training did not start. No real GPU activity. This is probably due to dataflow streaming. Check, if the dataflow streams datapoints and that images can be loaded.

**Comment by himasai9711** [comment]
is there any method to check that?
