### ISSUE TITLE
Publish Docker images on the Hub or Github Container Registry

### ISSUE THREAD

**Issue by alexkreidler** [deepdoctection/deepdoctection#189]
This would allow people to download pre-built images. The dependencies for this library are complex and sometimes conflict (e.g. when using conda/mamba), so using Docker avoids that problem.

You could add a Github Action to automatically build and push the images on pushes/PRs to main or new release tags.

**Comment by JaMe76** [comment]
Thanks for your suggestion. 

Will add it on the to-do-list.

Also reducing dependency complexity will be of top-priority.

**Comment by JaMe76** [comment]
Resolved with PR #232
