### ISSUE TITLE
how to set registered models config file ?

### ISSUE THREAD

**Issue by himasai9711** [deepdoctection/deepdoctection#191]
1) **question** 💥
i wanted to train the model using you documentation this:

[https://github.com/deepdoctection/deepdoctection/blob/master/docs/tutorials/training_and_logging.md](url)

Im unable to use the registered model give in the documentation to train my model
**Screenshots** 🖼
<img width="1046" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/bcc0fcaf-084b-4ea1-afb4-51210b0fdac4">

And when i tried to set the config path using this i got following error:
**Screenshots** 🖼
<img width="1046" alt="image" src="https://github.com/deepdoctection/deepdoctection/assets/75134122/debeb764-e87d-4832-9f73-cccc45c78d17">

2) **question** 💥
After changing that path to my config file how can i save my model file any method?

**Comment by JaMe76** [comment]
1.) 

> 1. **question** 💥
>    i wanted to train the model using you documentation this:
> 
> [https://github.com/deepdoctection/deepdoctection/blob/master/docs/tutorials/training_and_logging.md](url)
> 
> Im unable to use the registered model give in the documentation to train my model

I am unable to help if I do not have any error messages. Using the paths, configs and categories as input for the d2 training script should work.

2.) This is a different config setting that cannot be used to initialize Detectron2 config. You must use the config class as given in the d2 training script.

**Comment by himasai9711** [comment]
Another quest where is model file?
