### ISSUE TITLE
Linux installation issue - Installation from source

### ISSUE THREAD

**Issue by ShivaChaitanyaGurrala** [deepdoctection/deepdoctection#205]
**Bug** 💥
I am trying to install from source as it enables to tweak the pipeline and train. But in installation for `torch  pip install ".[source-pt]"` it is trying to install dependencies from "deepdoctection-0.26-py3-none-any.whl.metadata" instead of picking from requirments.txt. And  it is trying to install opencv-python==4.5.4.60 which internally trying to install numpy==1.21.2 which is not present. Is there a way update this wheel file to use opencv-python latest version? Or remove it from requirements and add it as prerequired libraries, so it can be installed separately? 

Also is there a way to pass local wheel file as setup option, so requirements could be updated ?  

**Expected behavior**  🧮 
Ideally setup.py should have installed all the dependencies required for deepdoctection without any issue

**Screenshots** 🖼
![image](https://github.com/deepdoctection/deepdoctection/assets/36737948/e78f8463-077c-481e-b083-b0abd83c1872)
![image](https://github.com/deepdoctection/deepdoctection/assets/36737948/cd40bac5-f532-4f91-96f7-a0b21913d928)

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Ubuntu Debian

**Additional context** 🧬
If necessary add some context related to the problem

**Comment by JaMe76** [comment]
Looks to be an issue due to Python 3.11 which I haven't tested yet. It should work with Python 3.10.

Installation doesn't use requirements.txt as there would have been to many installation options.
