### ISSUE TITLE
Download weights at container build time

### ISSUE THREAD

**Issue by adrianturcato** [deepdoctection/deepdoctection#206]
It would be great if we could add a check somewhere around here to see if the weight has already been downloaded. (https://github.com/deepdoctection/deepdoctection/blob/b952df8e99f4bfc6e4c69830b75196dfd0e1e323/deepdoctection/extern/model.py#L911)

The goal would be to run deepdoctection in an environment that does not necessarily have access to the internet. For example a container in a production system. 

Ideally the weights would be downloaded at install time, with an option to refresh at run time if desired. But the workaround is to build the pipeline at the build time of the container. And then check to see if the weights already exist at runtime. 

If you are open to some flavour of this suggestion, I would be happy to submit a contribution for review.

**Comment by JaMe76** [comment]
Thanks for the suggestion and I think it is important to have this logic. 
Currently it checks if download is necessary but I do not really know how it behaves if no connection is available. 

Always happy for suggestions, ideas and improvements!

**Comment by adrianturcato** [comment]
Hey Janis,

Okay thanks for the info. The errors I was receiving were more so regarding network connections blocked from intranet egress. I will think about putting a contribution together when I have a moment.

**Comment by adrianturcato** [comment]
It actually seems like hugging face hub should be working in this fashion, but appears like perhaps there is an issue in there somewhere: https://github.com/huggingface/huggingface_hub/blob/cbef4b6b8c9503f449d487d575a8daaa9c31c9f9/src/huggingface_hub/file_download.py#L568

**Comment by JaMe76** [comment]
With the upcoming release there will PyTorch GPU Docker images available at Docker hub

When building and refactoring the Dockerfile I have been re-thinking, if loading models at build time and "backing" them into the image would be ideal. They main problem is to agree on what model should be loaded. This ultimately depends on the config of the analyzer and could vary even more if you want to build something custom. Downloading all models is not an option as this would blow up your image to > 60 GB!

I therefore think, it would more natural to use volumes and keep everything that is in the cache (e.g. weights, configs, maybe even datasets) outside the image. To prepare everything in a secure environment you can download configs/models in advance. 

I have tested the setup with a new docker compose file and a container with gpu support without internet access and it works. The download function from `huggingface_hub` seems to be doing what it is supposed to do.

The image will be available in the Docker hub once the next release is ready (which I think will be tomorrow). 

Compare with  [378e1a0](https://github.com/deepdoctection/deepdoctection/commit/378e1a0edb3d8124a49ff3bd6ecc0d10af6852f7).

**Comment by JaMe76** [comment]
Closing with commit 6799b4c .
