### ISSUE TITLE
summary histogram error while custom training 

### ISSUE THREAD

**Issue by ShivaGurrala94** [deepdoctection/deepdoctection#207]
**Bug** 💥
I am tryining to train Detectron2 on custom dataset for that I am currently using CustomDataset Loader, while calling  train_d2_faster_rcnn method inside the loop it hits print_summary_histogra() in maputils.py

while debugging I found categories is a dictionary of labels but in code we are trying to access value from string object was the intenstion here to get value of each category ? if so could I modify the local code to just get self.categories[str(i)] instead of .value operation on it ?  
(Pdb) self.categories
{'1': 'figure', '2': 'list', '3': 'table', '4': 'text', '5': 'title'}

```
 if dd_logic:
        data = list(itertools.chain(*[[self.categories[str(i)].value, v] for i, v in enumerate(self.summary, 1)]))
 else:
        data = list(
                itertools.chain(*[[self.categories[str(i + 1)].value, v] for i, v in enumerate(self.summary[:-1])])
         )
```

**Expected behavior**  🧮 
It should have ideally got the categories and print the summary

**Screenshots** 🖼
![image](https://github.com/deepdoctection/deepdoctection/assets/138500985/7558cbcf-9230-4704-8eb1-78ec19acb3c0)

If possible, please add a screenshot of the error message, if possible

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Linux

**Additional context** 🧬
If necessary add some context related to the problem

**Comment by JaMe76** [comment]
`LabelSummarizer` requires `categories`  being a `Mapping[str, ObjectTypes]` not `Mapping[str, str]`. 

Category names are members of string `Enum`s as given in [utils/settings.py](https://github.com/deepdoctection/deepdoctection/blob/master/deepdoctection/utils/settings.py) and therefore always have a `value` attribute. Given that category names are already defined as `Enum`s you can build a dict like:

```
from deepdoctection.utils import get_type

{'1': get_type('figure'), '2': get_type('list'), '3': get_type('table'), '4': get_type('text'), '5': get_type('title')}
```

New category names have to be registered by defining a new class derived from  `ObjectTypes` as described [here](https://github.com/deepdoctection/notebooks/blob/main/Running_pre_trained_models_from_third_party_libraries.ipynb)
