### ISSUE TITLE
AttributeError: module 'cv2.dnn' has no attribute 'DictValue' while installing deepdoctection through pip

### ISSUE THREAD

**Issue by frivas-at-navteca** [deepdoctection/deepdoctection#209]
**Bug** 💥
Building a Docker image to run Deepdoctection in a Lambda function. While performing the installation in the following way (omitting information for the sake of shortness):

```
#19 [15/23] RUN pip3 install --no-cache-dir --upgrade deepdoctection[pt]
#19 1.929 Collecting opencv-python==4.5.4.60
#19 1.936   Downloading opencv_python-4.5.4.60-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.3 MB)
```

I can see the following error when testing Deepdoctection:

```
#21 [17/23] RUN python3 -c "import deepdoctection; dd = deepdoctection.get_dd_analyzer()"
#21 0.633 Traceback (most recent call last):
#21 0.633   File "<string>", line 1, in <module>
#21 0.633   File "/var/lang/lib/python3.9/site-packages/deepdoctection/__init__.py", line 14, in <module>
#21 0.633     from .utils.file_utils import _LazyModule, get_tf_version, pytorch_available, tf_available
#21 0.633   File "/var/lang/lib/python3.9/site-packages/deepdoctection/utils/__init__.py", line 9, in <module>
#21 0.633     from .context import *
#21 0.633   File "/var/lang/lib/python3.9/site-packages/deepdoctection/utils/context.py", line 32, in <module>
#21 0.633     from cv2 import imwrite
#21 0.633   File "/var/lang/lib/python3.9/site-packages/cv2/__init__.py", line 188, in <module>
#21 0.633     bootstrap()
#21 0.633   File "/var/lang/lib/python3.9/site-packages/cv2/__init__.py", line 182, in bootstrap
#21 0.633     if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
#21 0.633   File "/var/lang/lib/python3.9/site-packages/cv2/__init__.py", line 36, in __load_extra_py_code_for_module
#21 0.634     py_module = importlib.import_module(module_name)
#21 0.634   File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
#21 0.634     return _bootstrap._gcd_import(name[level:], package, level)
#21 0.634   File "/var/lang/lib/python3.9/site-packages/cv2/typing/__init__.py", line 169, in <module>
#21 0.634     LayerId = cv2.dnn.DictValue
#21 0.634 AttributeError: module 'cv2.dnn' has no attribute 'DictValue'
#21 ERROR: process "/bin/sh -c python3 -c \"import deepdoctection; dd = deepdoctection.get_dd_analyzer()\"" did not complete successfully: exit code: 1
```

**Expected behavior**  🧮 
The expected behavior is the installation goes through correctly.

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - I am using this image: public.ecr.aws/lambda/python:3.9

**Additional context** 🧬
I believe this is due the latest changes in the `setup.py` specifically the following line https://github.com/deepdoctection/deepdoctection/blob/7cf932b3b57def78b564040f5044da9a1fd38ffb/setup.py#L54 as the version specified in the `requirements.txt` differs. https://github.com/deepdoctection/deepdoctection/blob/7cf932b3b57def78b564040f5044da9a1fd38ffb/requirements.txt#L54 

I have tested it installing the version specified in the `setup.py` and it works correctly. I will be sending a PR that might solve this issue by bumping up the version of opencv-python in requirements.txt.

I also want to take the opportunity to thank you for creating this library, I have test a few other and this one is just the best.

**Comment by JaMe76** [comment]
Many thanks for spotting the issue! 

Will merge your PR soon.

**Comment by JaMe76** [comment]
Closing with PR #210
