### ISSUE TITLE
numpy.ndarray for an analyze input

### ISSUE THREAD

**Issue by reredata2** [deepdoctection/deepdoctection#217]
i have an example code bellow, 

`grayscale_image = cv2.cvtColor(cropped_image, cv2.COLOR_BGR2GRAY)`
`thresholded = cv2.threshold(grayscale_image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]`
`inverted = cv2.bitwise_not(thresholded)`

how make that `inverted` as an input? or only path for input analyze?

thank you

**Comment by JaMe76** [comment]
Thank you for your question.

This is currently not really possible without some hack.

I have been thinking for a while and the cleanest thing would be to 

1.)  write an `InvertedImageTransformer` derived from `deepdoctection.extern.base.ImageTransformer` and implementing the abstract method `transform`.

```
class InvertedImageTransformer(ImageTransformer):

def transform(self, np_img: ImageType) -> ImageType:
    grayscale_image = cv2.cvtColor(np_img, cv2.COLOR_BGR2GRAY)
    thresholded = cv2.threshold(grayscale_image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
    inverted = cv2.bitwise_not(thresholded)
    return inverted    
```

2.) Build an instance of the pipeline component: `SimpleTransformService` using the `InvertedImageTransformer`, e.g.

```
inverted_image =   InvertedImageTransformer()
simple_transform_component = SimpleTransformService(inverted_image)
```

3.) Plugging `simple_transform_component` at the first position of among all pipeline components. (NB. There is currently no method to a a component into the pipeline, so this is the hacky part.)

```
analyzer = get_dd_analyzer()
analyzer.pipeline_component.insert(0, simple_transform_component)
```

This will initially transform the image following your rules and pass the transformed image to all subsequent components.

**Comment by reredata2** [comment]
Thankyou for your answer

what i mean as input is like this
```python

grayscale_image = cv2.cvtColor(cropped_image, cv2.COLOR_BGR2GRAY)
thresholded = cv2.threshold(grayscale_image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
inverted = cv2.bitwise_not(thresholded)

df = analyzer.analyze(inverted) # this is the question i asked
```

so, I want to do text detection in certain parts only, so I crop it that area first, then I use numpy.ndarray as an input not a path, how to achieve that?

**Comment by JaMe76** [comment]
Passing an np.array as argument is not possible. 
The reason is, that reading an image should be done internally avoiding users to get trapped into loading issues (e.g. loading RGB instead of BGR).

But if you really want to pass a special np array, follow these steps:

 
```python
analyzer = get_dd_analyzer()

image = dd.Image(file_name="your_image_name", location="your_image_location") #parameters won't do anything but are required

image.image = inverted
 
df = dd.DataFromList(lst=[image])                    # define a stream by a list of images
df = analyzer.analyze(dataset_dataflow=df).   # pass the stream
```

**Comment by reredata2** [comment]
i see, thankyou for the answer. Another alternative is save the cropped image first then use saved image as input?

**Comment by JaMe76** [comment]
of course, this is another option...
