### ISSUE TITLE
IndexError in table segmentation service

### ISSUE THREAD

**Issue by BenHaselden** [deepdoctection/deepdoctection#228]
**Bug** 💥
Please describe the error you encoutered
I have a document where a table is detected, but no columns. A dummy column is added, but when the iou values for the column are calculated, they all fall below the hard-coded threshold of 0.0001 (the maximum value in the matrix is ~8e-5), which means the column is deactivated, the items array becomes an empty list and the reference to items[0] (line 740, segment.py) raises an IndexError.

**Expected behavior**  🧮 
Describe what you would have expected
Either being able to handle the items array being empty, or force it to always have at least 1 element.

**Screenshots** 🖼
If possible, please add a screenshot of the error message, if possible
<img width="723" alt="Screenshot 2023-09-21 at 14 44 19" src="https://github.com/deepdoctection/deepdoctection/assets/139141065/f04a1356-192d-45f3-b32b-2948a63332dd">

**Desktop (please complete the following information, if any other than the one in the install requirements):**

**Additional context** 🧬
If necessary add some context related to the problem

**Comment by JaMe76** [comment]
Closing with #277
