### ISSUE TITLE
Deepdoctection Notebook "Using LayoutLM for sequence classification" bug.

### ISSUE THREAD

**Issue by aiorga-sherpas** [deepdoctection/deepdoctection#241]
**Bug** 💥
You can't run the notebook "Using LayoutLM for sequence classification" because `dd.DoctrTextlineDetector()` can't be initiated without parameters anymore. Once solved there is an index error.
 

**Expected behavior**  🧮 
Run the notebook like intended. 

**Screenshots** 🖼
`dd.DoctrTextlineDetector()` Error:
<img width="1102" alt="Screenshot 2023-10-23 at 15 59 07" src="https://github.com/deepdoctection/deepdoctection/assets/148062545/9a00273f-46c4-4c88-a913-6301126dd9dc">

Error once solved:
<img width="1159" alt="Screenshot 2023-10-23 at 15 59 54" src="https://github.com/deepdoctection/deepdoctection/assets/148062545/046b2ff2-1126-4574-a796-13a6dc7606fa">

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 -MacOS

**Additional context** 🧬
I have created a fork to work this out, sadly still does not work.

**Comment by JaMe76** [comment]
Thanks for reporting. Will have a look as soon as I can.

**Comment by JaMe76** [comment]
1.) The notebook has been updated. It is now possible again to create a sub-dataset of `RVLCDIP` to run with LayoutLM. 
2.) The index problem results from the fact that images from `RVLCDIP` are 2-dim only and could not be loaded with the new `viz_handler`. This been fixed with #259 .

**Comment by JaMe76** [comment]
Closing with #259
