### ISSUE TITLE
Table Detection Error - Help

### ISSUE THREAD

**Issue by Dipankar1997161** [deepdoctection/deepdoctection#244]
Hello @JaMe76, 

Installed -> pip install deepdoctection.  (the minimal one)

I tried running the **inference** on an image and as well as a single page pdf and the results were same.
It is unable to detect the tables at the top of the page. do you know why this could be the case?

<img width="985" alt="Screenshot 2023-10-26 at 12 25 20" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/317421fa-5c33-4655-883c-26b8d98c7b57">

Is the inference part is a minimal implementation? Because just now I tried this on hugging face space and it detected all correctly. 

The one at the bottom is the huggingFace one.
![image](https://github.com/deepdoctection/deepdoctection/assets/85514219/408040b1-50c2-4bd0-8eb6-a4906db63637)

I don't think so, I have to train any models since it is working superb already. SO, 
It would be great if you help a bit on this.

**Comment by aiorga-sherpas** [comment]
Hello @Dipankar1997161, 

I have seen you closed this issue. Is everything working correctly?

If so, could you please describe what was the solution so future users with this same issue can benefit and avoid duplicating issues?

Thank you.

**Comment by Dipankar1997161** [comment]
> Hello @Dipankar1997161,
> 
> I have seen you closed this issue. Is everything working correctly?
> 
> If so, could you please describe what was the solution so future users with this same issue can benefit and avoid duplicating issues?
> 
> Thank you.

Thank you for reaching out. I actually closed since I felt its a silly request. But I did replicate the HuggingFace application and there is improvement for sure.   Sadly, It is detecting the first table in the pdf/image as a 'FIGURE'.    This is my replication without any post process
![image-17](https://github.com/deepdoctection/deepdoctection/assets/85514219/0da79383-5d6b-46c8-a586-6f38175e7e09)
 
This is the result of the HuggingFace space
![image-18](https://github.com/deepdoctection/deepdoctection/assets/85514219/fbe5ee6b-26cf-40f9-bbf0-6c8bf75cf724)


I am unsure what could be the reason now if it's detecting it as Figure 😅 or what can be done?  If you have any idea please help

**Comment by JaMe76** [comment]
dd_addons isn’t doing anything special. In fact, I am considering to remove it. The difference is the model that has been trained much longer on a much broader dataset.

**Comment by Dipankar1997161** [comment]
> dd_addons isn’t doing anything special. In fact, I am considering to remove it. The difference is the model that has been trained much longer on a much broader dataset.

Is it possible for you to provide the model for usage since it is probably closest to mere perfect for my tables. 
I am aware it may be a private work, but am access through email, would be great. Do let me know

**Comment by Dipankar1997161** [comment]
Closing as Solved
