### ISSUE TITLE
Information regarding  deepdoc libraries - dd_addons

### ISSUE THREAD

**Issue by Dipankar1997161** [deepdoctection/deepdoctection#245]
@JaMe76, 

I was trying to replicate your gradio project of deepdoc as seen in hugginface.  I have installed all but I am unsure what these
dd_addons are.

<img width="855" alt="Screenshot 2023-10-27 at 02 27 09" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/7008b2bb-ab19-45d0-be2f-f7485523311c">

Since I am not sure how to install them, I am getting 'Module not found error- dd_addons'

<img width="855" alt="Screenshot 2023-10-27 at 02 45 05" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/dc6343a3-79d2-4885-a8bb-e14da4ce817b">

Can you please clarify this? I will wait for your response

**Comment by JaMe76** [comment]
https://github.com/deepdoctection/deepdoctection/discussions/218

**Comment by Dipankar1997161** [comment]
Thanks for clarification.
