### ISSUE TITLE
PADDING effect for Table-Transformer - Clarification Required

### ISSUE THREAD

**Issue by Dipankar1997161** [deepdoctection/deepdoctection#246]
Hello @JaMe76, Thanks for clearing my previous answer. 

I read an issue regarding the 'Table Transformer' need some padding for proper coverage of table. I tried to create a config similar to config_dd_one.yaml but added the following. the weights and padding.
<img width="632" alt="Screenshot 2023-10-28 at 03 04 46" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/a4a0d592-3b2c-4374-82aa-15d61958a02a">

then I called the cfg like:

    _DD_ONE = "conf_dd_one.yaml"
    cfg = dd.set_config_by_yaml(path.join(getcwd(),_DD_ONE))
    cfg.freeze(freezed=False)
    cfg.DEVICE = "gpu"
    cfg.freeze()

upon printing the cfg to check if its overwritten and yes: 
<img width="958" alt="Screenshot 2023-10-28 at 03 05 50" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/8d055c4e-4cba-472d-a013-4e6b87472090">

Building the basic layout analyser

<img width="858" alt="Screenshot 2023-10-28 at 03 30 22" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/17b08135-57ea-4510-8ce9-ae192854a36b">

Analysing the image and passing build_analyzer
<img width="858" alt="Screenshot 2023-10-28 at 03 34 43" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/6fce68c0-256c-46db-8973-a6a101c6ef5f">

Built a similar gradio as hub space. 
<img width="858" alt="Screenshot 2023-10-28 at 03 35 03" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/a98406c8-0b9c-4fb6-9e66-aa2cd1caf7b9">

result has no change after Padding 150
![image(6)](https://github.com/deepdoctection/deepdoctection/assets/85514219/e146314c-2fe6-4966-8030-4a072f0a4e4d)

No Padding
![image(8)](https://github.com/deepdoctection/deepdoctection/assets/85514219/173f8f5b-bffd-4d03-8170-4b8c5f358f19)

Maybe I did some mistake.... If you can point out the issue, I can correct and rebuilt my system.   Do I need to create a function for custom padding ? since I have included it in the config but it has no effect :(

Thank you once again

**Comment by JaMe76** [comment]
What you are doing is padding around the full page, which will not really affect the prediction output of the detection model.
Table transformer needs padding once you infer table structure. First you will have to crop the table box from the detection model and then you must pad around the cropped table. 
This is necessary because table recognition model has been trained on padded tables.   

You can check [this discussion](https://github.com/deepdoctection/deepdoctection/discussions/116) where I build a pipeline for table transformer from scratch before it was possible to use this model with the built-in analyzer.

I just realized that the [docs](https://deepdoctection.readthedocs.io/en/latest/tutorials/analyzer_configuration_notebook/) are misleading because layout does not require padding. Only row/column/spanning cell does.

**Comment by Dipankar1997161** [comment]
Thanks for the response @JaMe76, I was fully able to construct the table extraction from scratch. Although the padding didn't FULLY cover the entire table from the sides, The OCR is working good (**I used Tessaract**)

I used the **PadTransfrom** function as xyxy mode.  Increasing the padding, at times shrinks the structure of the table (WHICH I FIND WEIRD) -  Shouldn't it increase overall.  or is that due to the inbuilt Padding function here

![image(35)](https://github.com/deepdoctection/deepdoctection/assets/85514219/4ccb5f6a-0ad5-4e0c-bee7-e73c82085131)

But for this image, when I created the HTML table as same as HubSpace,  the larger tables sometimes are incomplete...see

<img width="1512" alt="Screenshot 2023-10-29 at 02 17 29" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/53a38e61-0528-4203-b57d-9d758cae56eb">


**If you take a closer look, Subject 394 is not in the HTML and Also the content is swapped at times (I mean the correct number is under correct value but the layout is new - SEE IMAGE BELOW)..  This is also the case for many other.. is it the HTML problem??**

<img width="872" alt="Screenshot 2023-10-29 at 02 32 00" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/6f8c5e25-f9af-4ca3-aa8c-a9cb70ae9985">

**It would great to hear from you on this matter, on what can be done.. here is my config and my analyzer**

<img width="1125" alt="Screenshot 2023-10-29 at 02 21 25" src="https://github.com/deepdoctection/deepdoctection/assets/85514219/29b14326-bfb7-4d9d-8244-c9c267937bfb">


ANALYZER:

  pipe_component_list: List[PipelineComponent] = []
  
      # layout - table
      layout_config_path = ModelCatalog.get_full_path_configs(cfg.PT.LAYOUT.CONFIGS)
      layout_weights_path = ModelDownloadManager.maybe_download_weights_and_configs(cfg.PT.LAYOUT.WEIGHTS)
      layout_preconfig_path = ModelCatalog.get_full_path_preprocessor_configs(cfg.PT.LAYOUT.CONFIGS)
      profile_layout = ModelCatalog.get_profile(cfg.PT.LAYOUT.WEIGHTS)
      categories_layout = profile_layout.categories
      
      assert categories_layout is not None
      assert layout_weights_path is not None
      
      d_layout = HFDetrDerivedDetector(layout_config_path, layout_weights_path,layout_preconfig_path, categories_layout, device=cfg.DEVICE)
      layout = ImageLayoutService(d_layout, to_image=True, crop_image=True)
      pipe_component_list.append(layout)
  
      
      nms_service = dd.AnnotationNmsService(nms_pairs=cfg.LAYOUT_NMS_PAIRS.COMBINATIONS,
                                            thresholds=cfg.LAYOUT_NMS_PAIRS.THRESHOLDS)
      pipe_component_list.append(nms_service)
      if cfg.TAB:
          
          structure_config_path = ModelCatalog.get_full_path_configs(cfg.PT.STRUCTURE.CONFIGS)
          structure_weights_path = ModelDownloadManager.maybe_download_weights_and_configs(cfg.PT.STRUCTURE.WEIGHTS)
          structure_preprocessor_config = ModelCatalog.get_full_path_preprocessor_configs(cfg.PT.STRUCTURE.CONFIGS)
          profile = ModelCatalog.get_profile(cfg.PT.STRUCTURE.WEIGHTS)
          categories_structure = profile.categories
          
          hf_table_structure = HFDetrDerivedDetector(structure_config_path,
                                                  structure_weights_path,
                                                  structure_preprocessor_config,
                                                  categories_structure,
                                                  filter_categories=[LayoutType.table])
      
          padder = PadTransform(top=cfg.PT.STRUCTURE.PAD.TOP,right=cfg.PT.STRUCTURE.PAD.RIGHT,
                                bottom=cfg.PT.STRUCTURE.PAD.BOTTOM,left=cfg.PT.STRUCTURE.PAD.LEFT, mode=cfg.PT.STRUCTURE.PAD.MODE)
          
          detect_result_generator = DetectResultGenerator(categories_structure, exclude_category_ids=["1","3","4","5","6"])
          
          structure = SubImageLayoutService(hf_table_structure,
                                            LayoutType.table,
                                            {1: 6, 2:7, 3:8, 4:9, 5:10, 6:11},
                                            detect_result_generator,
                                            padder)
          pipe_component_list.append(structure)
          
          segment = PubtablesSegmentationService(cfg.SEGMENTATION.ASSIGNMENT_RULE,
                                               cfg.SEGMENTATION.THRESHOLD_ROWS,
                                               cfg.SEGMENTATION.THRESHOLD_COLS,
                                               cfg.SEGMENTATION.FULL_TABLE_TILING,
                                               cfg.SEGMENTATION.REMOVE_IOU_THRESHOLD_ROWS,
                                               cfg.SEGMENTATION.REMOVE_IOU_THRESHOLD_COLS,
                                               cfg.SEGMENTATION.CELL_CATEGORY_ID,
                                               stretch_rule=cfg.SEGMENTATION.STRETCH_RULE)
          pipe_component_list.append(segment)
  
          
          if cfg.TAB_REF:
              table_segmentation_refinement = dd.TableSegmentationRefinementService()
              pipe_component_list.append(table_segmentation_refinement)
          
      if cfg.OCR:
  
          tess_ocr_config_path = ModelCatalog.get_full_path_configs(cfg.TEXT.CONFIG.TESS_OCR)
          d_tess_ocr = TesseractOcrDetector(
          tess_ocr_config_path, config_overwrite=[f"LANGUAGES={cfg.LANG}"] if cfg.LANG is not None else None
      )
          text = TextExtractionService(d_tess_ocr)
          pipe_component_list.append(text)
      
          match = MatchingService(
              parent_categories=cfg.WORD_MATCHING.PARENTAL_CATEGORIES,
              child_categories=LayoutType.word,
              matching_rule=cfg.WORD_MATCHING.RULE,
              threshold=cfg.WORD_MATCHING.THRESHOLD,
              max_parent_only=cfg.WORD_MATCHING.MAX_PARENT_ONLY
          )
          pipe_component_list.append(match)
      
          order = TextOrderService(
              text_container=cfg.TEXT_ORDERING.TEXT_CONTAINER,
              floating_text_block_categories=cfg.TEXT_ORDERING.FLOATING_TEXT_BLOCK,
              text_block_categories=cfg.TEXT_ORDERING.TEXT_BLOCK_CATEGORIES,
              starting_point_tolerance = cfg.TEXT_ORDERING.STARTING_POINT_TOLERANCE,
              broken_line_tolerance = cfg.TEXT_ORDERING.BROKEN_LINE_TOLERANCE
          )
          pipe_component_list.append(order)
          
      pipe = dd.DoctectionPipe(pipeline_component_list=pipe_component_list)
  
      #post_processor = PostProcessor("deepdoctection", **credentials_kwargs)
      #post_service = PostProcessorService(post_processor)
      #pipe_component_list.append(post_service)
  
      return pipe
      
Do let me know any potential ways to improve things. Any other service or so

**Comment by Dipankar1997161** [comment]
Lastly, is it possible to collect the table data in CSV format from deepdoctection??  If so how.. Do I need to create a separate function myself or there is something in the repo to help?  @JaMe76  Thanks once again

**Comment by Dipankar1997161** [comment]
Solved the Structural problem. So closing this thread as well

**Comment by Dipankar1997161** [comment]
Solved the Structure problem. Closing the thread
