### ISSUE TITLE
Default Jdeskew image transformer doesn't work for negative rotations

### ISSUE THREAD

**Issue by domaschh** [deepdoctection/deepdoctection#258]
**Bug** 💥
Please describe the error you encoutered
I tried to implement the Jdeskewer service and noticed that for images rotated negatively this doesn't work.
**Expected behavior**  🧮 
Describe what you would have expected
This image was not correctly rotated as the rotation is about -4.

**Screenshots** 🖼
If possible, please add a screenshot of the error message, if possible

**Desktop (please complete the following information, if any other than the one in the install requirements):**

```python
class Jdeskewer(ImageTransformer):
    """
    Deskew an image following <https://phamquiluan.github.io/files/paper2.pdf>. It allows to determine that deskew angle
    up to 45 degrees and provides the corresponding rotation so that text lines range horizontally.
    """

    def __init__(self, min_angle_rotation: float = 2.0):
        self.name = "jdeskew_transform"
        self.min_angle_rotation = min_angle_rotation

    def transform(self, np_img: ImageType) -> ImageType:
        angle = get_angle(np_img)

        if angle > self.min_angle_rotation:
            return rotate(np_img, angle)
        return np_img

    @classmethod
    def get_requirements(cls) -> List[Requirement]:
        """
        Get a list of requirements for running the detector
        """
        return [get_jdeskew_requirement()]
```
        
Lookign at the deskewer class maybe the default min_angle_rotation is always positive (2). Setting it to a very low negative number works. Maybe it would be nice to compare the absolute angle of the image against the min angle rotation. (the image from above has rotation ~ -4

```python
    def transform(self, np_img: ImageType) -> ImageType:
        angle = get_angle(np_img)

        if abs(angle) > self.min_angle_rotation:
            return rotate(np_img, angle)
        return np_img```

**Comment by JaMe76** [comment]
Closing with #305
