### ISSUE TITLE
Layout and Text Detection Discrepancy Between Docker Image (PyTorch) and Hugging Face Live Version

### ISSUE THREAD

**Issue by Faizan-hub** [deepdoctection/deepdoctection#266]
**Bug** 💥
I have run the docker image, pytorch version to detect layout and text in the image and pdf, but it detects only two tables and titles, while in the live version deployed on huggingface, it detects well.

**Expected behavior**  🧮 
I want to have same layouts as detected in live version.

**Screenshots** 🖼
Images are private

**Desktop (Linux)

**Comment by JaMe76** [comment]
https://huggingface.co/spaces/deepdoctection/deepdoctection/discussions/3
