### ISSUE TITLE
AttributeError: module 'deepdoctection.extern' has no attribute 'D2FrcnnDetector'

### ISSUE THREAD

**Issue by yashsandansing** [deepdoctection/deepdoctection#271]
**Bug** 💥
`AttributeError: module 'deepdoctection.extern' has no attribute 'D2FrcnnDetector'` when running the 

`Running_pre_trained_models_from_third_party_libraries.ipynb` notebook. 

More specifically on the `d2_detector = dd.D2FrcnnDetector(path_config,path_weights,categories)` line from the 14th executed cell

**Expected behavior**  🧮 
The detector should've loaded

**Screenshots** 🖼
![Screenshot 2023-11-24 205925](https://github.com/deepdoctection/deepdoctection/assets/48054260/986a52b2-919a-42ed-ad9d-e232300119b7)

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - Notebook - Colab
 - Requirements installed one first line - `!pip install --quiet tf2onnx python-dotenv==1.0.0 torch==1.12.0 torchvision==0.13.0 git+https://github.com/deepdoctection/deepdoctection#egg=deepdoctection[hf]`

**Comment by JaMe76** [comment]
`deepdoctection[hf]` does not install Detectron2. 

Either use `deepdoctection[source-pt]` to have Detectron2 as dependency or you need to install it separately.
