### ISSUE TITLE
Poppler not found

### ISSUE THREAD

**Issue by yashsandansing** [deepdoctection/deepdoctection#272]
**Bug** 💥
`PopplerNotFound: Poppler not found. Please install or add to your PATH.` when using 

```
dp = next(df_iter)
```
Everyting works fine if I install a normal `deepdoctection` using `pip` but when I use `source-pt` or `tf`, I get this issue.
I've tried to verify if poppler is installed using `pdf2image` and it works fine. But I don't know why only here I get this issue

**Expected behavior**  🧮 
The pipeline loads fine

**Screenshots** 🖼
![poppler](https://github.com/deepdoctection/deepdoctection/assets/48054260/831612ba-bcad-4aad-9504-a28af5d0276a)

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: google colab

**Additional context** 🧬
I've installed poppler using this command:
`!sudo apt-get install poppler-utils`

**Comment by JaMe76** [comment]
I do not have an answer yet why the code breaks but it occurs here: 

ˋˋˋ
if pdf_to_ppm_available():
        command = "pdftoppm"
    elif pdf_to_cairo_available():
        command = "pdftocairo"
    else:
        raise PopplerNotFound("Poppler not found. Please install or add to your PATH.")
ˋˋˋ

Can you try if one of the CLI-commands pdftocairo or pdftoppm are available? Maybe I should add pdf2image …

**Comment by yumikim381** [comment]
I have encountered the same issue

**Comment by wolfassi123** [comment]
@yashsandansing  Did you manage to make it run?

**Comment by yashsandansing** [comment]
@wolfassi123 just managed get it working. this is my code for reference:
```
!pip install --quiet tf2onnx python-dotenv==1.0.0 torch==1.12.0 torchvision==0.13.0 git+https://github.com/deepdoctection/deepdoctection#egg=deepdoctection[hf]
!pip install timm --quiet

import deepdoctection as dd
from deepdoctection.dataflow.serialize import DataFromList
import time
from botocore.config import Config

deepdoc = dd.get_dd_analyzer()

df = deepdoc.analyze(path = "doc.pdf")  # setting up pipeline
df.reset_state()                 # Trigger some initialization

import matplotlib.pyplot as plt

doc = iter(df)
page = next(doc)

image = page.viz()
plt.figure(figsize = (25,17))
plt.axis('off')
plt.imshow(image)

```
also, if I use a `config_overwrite` arguments in `dd.get_dd_analyzer`, it doesn't work and gives me some other error.
Normally, works.
I have installed a lot of unused stuff here, but it's because I had to comb through a bit of old code.
if it doesn't work, lmk. I'll share a new notebook with my code in it

**Comment by wolfassi123** [comment]
> @wolfassi123 just managed get it working. this is my code for reference:
> 
> ```
> !pip install --quiet tf2onnx python-dotenv==1.0.0 torch==1.12.0 torchvision==0.13.0 git+https://github.com/deepdoctection/deepdoctection#egg=deepdoctection[hf]
> !pip install timm --quiet
> 
> import deepdoctection as dd
> from deepdoctection.dataflow.serialize import DataFromList
> import time
> from botocore.config import Config
> 
> deepdoc = dd.get_dd_analyzer()
> 
> df = deepdoc.analyze(path = "doc.pdf")  # setting up pipeline
> df.reset_state()                 # Trigger some initialization
> 
> import matplotlib.pyplot as plt
> 
> doc = iter(df)
> page = next(doc)
> 
> image = page.viz()
> plt.figure(figsize = (25,17))
> plt.axis('off')
> plt.imshow(image)
> ```
> 
> also, if I use a `config_overwrite` arguments in `dd.get_dd_analyzer`, it doesn't work and gives me some other error. Normally, works. I have installed a lot of unused stuff here, but it's because I had to comb through a bit of old code. if it doesn't work, lmk. I'll share a new notebook with my code in it

Hey @yashsandansing , thank you for sharing your code. I tried it but unfortunately I am still getting the `Poppler not found` error on Colab. Do you have a working notebook that can be shared?

**Comment by yashsandansing** [comment]
try this one
@wolfassi123 
https://colab.research.google.com/drive/1nk7u8lQOJbO9H8xSVYTpzVdV8kuPAZla?usp=sharing
have added additional libraries needed for this
