### ISSUE TITLE
Support for microsoft/table-transformer-structure-recognition-v1.1-all

### ISSUE THREAD

**Issue by ee-lang** [deepdoctection/deepdoctection#273]
Is there a way to use the enhanced TATR structure recognition (1.1)?
In the HF repo there's no pytorch_model.bin (only model.safetensors).

**Enhancement** 🚀
Support for microsoft/table-transformer-structure-recognition-v1.1-all

**Motivation**  💪 
It is better at defining the table structure.

**Alternatives** ⚖️
It's basic version (1.0)

**Comment by JaMe76** [comment]
The model itself is the same as the first recognition model.

Differences are training procedure and the fact that padding is not necessary anymore when running in inference mode.

So you can take the original TATR checkpoint, convert the checkpoint using the older script here: 

https://github.com/huggingface/transformers/blob/main/src/transformers/models/table_transformer/convert_table_transformer_to_hf.py

to create a .pt checkpoint.

You will then have to add the model to the ModelCatalog as described [here](https://github.com/deepdoctection/notebooks/blob/main/Running_pre_trained_models_from_third_party_libraries.ipynb). 

I have it on my agenda, but this will definitely take some take.
