### ISSUE TITLE
I have downloaded package but cant get it installed due to dependency errors

### ISSUE THREAD

**Issue by forwardvision** [deepdoctection/deepdoctection#274]
Need some help. I have installed torchvision still it says ModuleNotFoundError: No module named 'torchvision'

**Comment by JaMe76** [comment]
Apologies for the delayed response. 

Unfortunately, based on the information provided, I am unable to offer assistance as the details are not sufficient.

To better assist you, could you please provide additional information such as the operating system (OS), Python version, deep learning framework, and the installation mode of deepdoctection? Bug reports usually follow a specific template. Using this template might streamline the process and ensure that all necessary information is included.

Your cooperation in providing these details will greatly facilitate our efforts to address and resolve the issue. 

Thank you for your understanding.

**Comment by forwardvision** [comment]
I pursued the library after seeing the impressive results in the hugging face demo. I invested 4 days installing, getting this to work and testing it....only to come to know that the model used in demo is not available for public use(which is fine)

My suggestion @JaMe76 is that a note indicating this clearly should be put on the demo page at huggingface so that folks trying this know it clearly and choose whether they want to invest(waste)  time in this or not!

**Comment by JaMe76** [comment]
I apologize for your wasted time and have added a note regarding the closed sourced models at the Huggingface Space.

**Comment by forwardvision** [comment]
@JaMe76 Thanks so much...
