### ISSUE TITLE
 File downloaded from deepdoctection/d2_casc_rcnn_X_32xd4_50_FPN_GN_2FC_publaynet_inference_only does not match the expected size!

### ISSUE THREAD

**Issue by FeU-aKlos** [deepdoctection/deepdoctection#290]
**Bug** 💥
I try to use deepdoctection, but while executing my script, I get the following errors:

ERR  File downloaded from deepdoctection/d2_casc_rcnn_X_32xd4_50_FPN_GN_2FC_publaynet_inference_only does not match the expected size! You may have downloaded a broken file, or the upstream may have modified the file.
ERR  File downloaded from deepdoctection/d2_casc_rcnn_X_32xd4_50_FPN_GN_2FC_pubtabnet_rc_inference_only does not match the expected size! You may have downloaded a broken file, or the upstream may have modified the file.
ERR  File downloaded from deepdoctection/d2_casc_rcnn_X_32xd4_50_FPN_GN_2FC_pubtabnet_c_inference_only does not match the expected size! You may have downloaded a broken file, or the upstream may have modified the file.

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - devcontainer on Ubuntu 22.04 LTS
 - deepdoctection version 0.30

**Comment by JaMe76** [comment]
This error log occurs if the download file does not have the expected size provided by the `ModelCatalog`. It should rather be a warning and on some machines I have spotted that the Python`s file size estimation does not always give you the same value.

Ignoring this log, may I ask if the code you are running terminates with an exception?

**Comment by FeU-aKlos** [comment]
@JaMe76 I see, no the code does not terminate with an exception.

**Comment by JaMe76** [comment]
Thanks for the reply. 

I will change this error log and turn it into a warning to reduce confusion.

**Comment by k3ntar0** [comment]
I am encountering the exact same error in my environment.
- Macbook Pro M1 Pro
- poetry
- `deepdoctection = "^0.30"`

**Comment by JaMe76** [comment]
Fixed with #292
