### ISSUE TITLE
Error in running in replit. 

### ISSUE THREAD

**Issue by AbhayMishraVK** [deepdoctection/deepdoctection#291]
I am running it in the deepDoctection in the replit, So I am getting the error while making analyzer. 
analyzer = dd.get_dd_analyzer()

The error coming is -> WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue. 
OSError: cannot load library 'pango-1.0-0': pango-1.0-0: cannot open shared object file: No such file or directory. Additionally, ctypes.util.find_library() did not manage to locate a library called 'pango-1.0-0'. 

I tried everything to install this in replit, but nothing work, please check the issue  and tell me How to install it.

**Comment by JaMe76** [comment]
`WeasyPrint` is a third party library used by `DocTr` and unfortunately I do not have experience with it. 

But I know that the installation might cause some problems.
