### ISSUE TITLE
Same line detection fails.

### ISSUE THREAD

**Issue by abhipn** [deepdoctection/deepdoctection#297]
@JaMe76  I have a document like below:

<img width="1350" alt="Screenshot 2024-03-10 at 11 35 36 PM" src="https://github.com/deepdoctection/deepdoctection/assets/47491248/272d923b-8b15-4409-bb3a-687a5f63956a">

Code:

```
import deepdoctection as dd

analyzer = dd.get_dd_analyzer()
doc_pred = analyzer.analyze(path="example_doc.pdf")
doc_pred.reset_state()
doc = iter(doc_pred)
page = next(doc)
print(page.text)
```

Text Output:

> 38.3
> Lithium metal and lithium ion batteries
> 38.3.1
> Purpose
> This section presents the procedures to be followed for the classification of lithium metal and lithium ion cells and batteries (see UN Nos. 3090, 3091, 3480 and 3481, and the applicable special provisions of Chapter 3.3 of the Model Regulations).
> 38.3.2
> Scope

Text in the same line is breaking into different line, How can I control this behaviour? @JaMe76 

For example 

> 38.3.1 Purpose

 is split into:
 

> 38.3.1
> Purpose

**Comment by JaMe76** [comment]
You can control line break to some extent by tweaking some of the following variables:

```
TEXT_ORDERING.STARTING_POINT_TOLERANCE
TEXT_ORDERING.BROKEN_LINE_TOLERANCE
TEXT_ORDERING.HEIGHT_TOLERANCE
TEXT_ORDERING.PARAGRAPH_BREAK
```

You can find a description of these variables in the docstrings here:
 https://github.com/deepdoctection/deepdoctection/blob/9658119bc9ad786d8c49e665569ec1caceccbee6/deepdoctection/pipe/order.py#L448
