### ISSUE TITLE
Handling skew image

### ISSUE THREAD

**Issue by phamquiluan** [deepdoctection/deepdoctection#30]
**Enhancement** 🚀
The ability to handling skew document image.

**Motivation**  💪 
Ensuring the document image is in a straight position is beneficial for subsequent steps.

**Additional context** 🧬
There is a package that you can use, https://github.com/phamquiluan/jdeskew

**Comment by JaMe76** [comment]
Thank you very much for suggesting the enhancement. I was actually considering added this feature as well. I will take a look at your suggestion to see how it could be integrated.
