### ISSUE TITLE
ModuleNotFoundError: No module named 'tf2onnx'

### ISSUE THREAD

**Issue by yumikim381** [deepdoctection/deepdoctection#300]
**Bug** 💥
When installation on google colab : 
!pip install deepdoctection[pt]
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
!apt-get install poppler-utils
And running code "import deepdoctection as dd
import cv2
from pathlib import Path
from matplotlib import pyplot as plt
from IPython.core.display import HTML

config_overwrite = ["OCR.USE_TESSERACT=False","OCR.USE_DOCTR= True","LANGUAGE='deu'"]
analyzer = dd.get_dd_analyzer(config_overwrite=config_overwrite)"

I get "ModuleNotFoundError: No module named 'tf2onnx'" error. "
More concretely:
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-df71d1ae7d94>](https://localhost:8080/#) in <cell line: 8>()
      6 
      7 config_overwrite = ["OCR.USE_TESSERACT=False","OCR.USE_DOCTR= True","LANGUAGE='deu'"]
----> 8 analyzer = dd.get_dd_analyzer(config_overwrite=config_overwrite)

[/usr/local/lib/python3.10/dist-packages/deepdoctection/utils/file_utils.py](https://localhost:8080/#) in __getattr__(self, name)
    713             value = self._get_module(name)
    714         elif name in self._class_to_module.keys():  # pylint: disable=C0201
--> 715             module = self._get_module(self._class_to_module[name])
    716             value = getattr(module, name)
    717         else:

[/usr/local/lib/python3.10/dist-packages/deepdoctection/utils/file_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
    723     @no_type_check
    724     def _get_module(self, module_name: str):
--> 725         return importlib.import_module("." + module_name, self.__name__)
    726 
    727     @no_type_check

[/usr/lib/python3.10/importlib/__init__.py](https://localhost:8080/#) in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.10/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.10/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.10/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.10/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.10/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.10/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

[/usr/local/lib/python3.10/dist-packages/deepdoctection/analyzer/__init__.py](https://localhost:8080/#) in <module>
     20 """
     21 
---> 22 from .dd import *

[/usr/local/lib/python3.10/dist-packages/deepdoctection/analyzer/dd.py](https://localhost:8080/#) in <module>
     31 
     32 from ..extern.base import ObjectDetector
---> 33 from ..extern.doctrocr import DoctrTextlineDetector, DoctrTextRecognizer
     34 from ..extern.model import ModelCatalog, ModelDownloadManager
     35 from ..extern.pdftext import PdfPlumberTextDetector

[/usr/local/lib/python3.10/dist-packages/deepdoctection/extern/__init__.py](https://localhost:8080/#) in <module>
     23 from .base import *
     24 from .deskew import *
---> 25 from .doctrocr import *
     26 from .fastlang import *
     27 from .hfdetr import *

[/usr/local/lib/python3.10/dist-packages/deepdoctection/extern/doctrocr.py](https://localhost:8080/#) in <module>
     41 
     42 if doctr_available() and ((tf_addons_available() and tf_available()) or pytorch_available()):
---> 43     from doctr.models.detection.predictor import DetectionPredictor  # pylint: disable=W0611
     44     from doctr.models.detection.zoo import detection_predictor
     45     from doctr.models.preprocessor import PreProcessor

[/usr/local/lib/python3.10/dist-packages/doctr/__init__.py](https://localhost:8080/#) in <module>
----> 1 from . import io, models, datasets, transforms, utils
      2 from .file_utils import is_tf_available, is_torch_available
      3 from .version import __version__  # noqa: F401

[/usr/local/lib/python3.10/dist-packages/doctr/models/__init__.py](https://localhost:8080/#) in <module>
      1 from . import artefacts
----> 2 from .classification import *
      3 from .detection import *
      4 from .recognition import *
      5 from .zoo import *

[/usr/local/lib/python3.10/dist-packages/doctr/models/classification/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .mobilenet import *
      2 from .resnet import *
      3 from .vgg import *
      4 from .magc_resnet import *
      5 from .vit import *

[/usr/local/lib/python3.10/dist-packages/doctr/models/classification/mobilenet/__init__.py](https://localhost:8080/#) in <module>
      2 
      3 if is_tf_available():
----> 4     from .tensorflow import *
      5 elif is_torch_available():
      6     from .pytorch import *

[/usr/local/lib/python3.10/dist-packages/doctr/models/classification/mobilenet/tensorflow.py](https://localhost:8080/#) in <module>
     13 from tensorflow.keras.models import Sequential
     14 
---> 15 from ....datasets import VOCABS
     16 from ...utils import conv_sequence, load_pretrained_params
     17 

[/usr/local/lib/python3.10/dist-packages/doctr/datasets/__init__.py](https://localhost:8080/#) in <module>
      1 from doctr.file_utils import is_tf_available
      2 
----> 3 from .generator import *
      4 from .cord import *
      5 from .detection import *

[/usr/local/lib/python3.10/dist-packages/doctr/datasets/generator/__init__.py](https://localhost:8080/#) in <module>
      2 
      3 if is_tf_available():
----> 4     from .tensorflow import *
      5 elif is_torch_available():
      6     from .pytorch import *  # type: ignore[assignment]

[/usr/local/lib/python3.10/dist-packages/doctr/datasets/generator/tensorflow.py](https://localhost:8080/#) in <module>
      6 import tensorflow as tf
      7 
----> 8 from .base import _CharacterGenerator, _WordGenerator
      9 
     10 __all__ = ["CharacterGenerator", "WordGenerator"]

[/usr/local/lib/python3.10/dist-packages/doctr/datasets/generator/base.py](https://localhost:8080/#) in <module>
     12 from doctr.utils.fonts import get_font
     13 
---> 14 from ..datasets import AbstractDataset
     15 
     16 

[/usr/local/lib/python3.10/dist-packages/doctr/datasets/datasets/__init__.py](https://localhost:8080/#) in <module>
      2 
      3 if is_tf_available():
----> 4     from .tensorflow import *
      5 elif is_torch_available():
      6     from .pytorch import *  # type: ignore[assignment]

[/usr/local/lib/python3.10/dist-packages/doctr/datasets/datasets/tensorflow.py](https://localhost:8080/#) in <module>
     13 from doctr.io import read_img_as_tensor, tensor_from_numpy
     14 
---> 15 from .base import _AbstractDataset, _VisionDataset
     16 
     17 __all__ = ["AbstractDataset", "VisionDataset"]

[/usr/local/lib/python3.10/dist-packages/doctr/datasets/datasets/base.py](https://localhost:8080/#) in <module>
     14 from doctr.utils.data import download_from_url
     15 
---> 16 from ...models.utils import _copy_tensor
     17 
     18 __all__ = ["_AbstractDataset", "_VisionDataset"]

[/usr/local/lib/python3.10/dist-packages/doctr/models/utils/__init__.py](https://localhost:8080/#) in <module>
      2 
      3 if is_tf_available():
----> 4     from .tensorflow import *
      5 elif is_torch_available():
      6     from .pytorch import *  # type: ignore[assignment]

[/usr/local/lib/python3.10/dist-packages/doctr/models/utils/tensorflow.py](https://localhost:8080/#) in <module>
     10 
     11 import tensorflow as tf
---> 12 import tf2onnx
     13 from tensorflow.keras import Model, layers
     14 

ModuleNotFoundError: No module named 'tf2onnx'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Expected behavior**  🧮 
On the readme it says i should be able to run DocTR with pytorch. 
Do you know how i could fix this except for downloading tensorflow version of deepdoctectron as well?

**Comment by JaMe76** [comment]
Running deepdoctection PyTorch on Colab turns out to be quite messy because Tensorflow is pre-installed and the internal logic expects to have all Tensorflow dependencies to be installed as well. 

Therefore, I do not have any other idea to install all Tensorflow dependencies as well.   They can be found [here](https://github.com/deepdoctection/deepdoctection/blob/9658119bc9ad786d8c49e665569ec1caceccbee6/setup.py#L151).

But I will take the issue to check if there is a possibility (e.g. by using environment variables) to enforce using PyTorch only even if Tensorflow is installed.

**Comment by yumikim381** [comment]
Thanks a lot for the explanation :D

**Comment by yumikim381** [comment]
I 've noticed that just by adding this line 
"import os
os.environ['USE_TORCH'] = '1'" 
I can avoid this issue
