### ISSUE TITLE
No module named 'doctr.models' error when running dd.get_dd_analyzer()

### ISSUE THREAD

**Issue by pfan-well** [deepdoctection/deepdoctection#306]
Cannot run the code 
```analyzer = dd.get_dd_analyzer(config_overwrite=
   ["PT.LAYOUT.WEIGHTS=microsoft/table-transformer-detection/pytorch_model.bin",   # TATR table detection model
    "PT.ITEM.WEIGHTS=microsoft/table-transformer-structure-recognition/pytorch_model.bin",  # TATR table segmentation model
    "PT.ITEM.FILTER=['table']",
    "OCR.USE_DOCTR=True",  # we disable Tesseract and use DocTr as OCR engine
    "OCR.USE_TESSERACT=False",
                        ])
```
Got error:
```ModuleNotFoundError: No module named 'doctr.models'```

doctr version = 1.9.0 (also tried a few lower version 1.4.0/1.7.0, etc to no avail)

OS: Mac OS X Sonoma 14.4

**Comment by JaMe76** [comment]
What install mode did you use for deepdoctection? [pt], [source-pt], … 

If you run

```python

import deepdoctection as dd

print(dd.doctr_available())
```

what is the output?

**Comment by pfan-well** [comment]
Here is the output.
<img width="246" alt="Screenshot 2024-04-04 at 8 31 34 AM" src="https://github.com/deepdoctection/deepdoctection/assets/147097992/bd150512-371f-4a30-b395-1ca0879e0e71">

**Comment by JaMe76** [comment]
If you are referring to [this package](https://pypi.org/project/doctr/), than it has nothing to do with the OCR-Package [DocTr](https://github.com/mindee/doctr). 

You need to install [python-doctr](https://pypi.org/project/python-doctr/).

**Comment by pfan-well** [comment]
Ok this resolved it. Thank you.

**Comment by subra-66** [comment]
> If you are referring to [this package](https://pypi.org/project/doctr/), than it has nothing to do with the OCR-Package [DocTr](https://github.com/mindee/doctr).
> 
> You need to install [python-doctr](https://pypi.org/project/python-doctr/).
> 
> DocTr latest release is 0.8.1.

This solved the issue.  Thank you.
