### ISSUE TITLE
Colab .cache weights and config

### ISSUE THREAD

**Issue by krupeshp** [deepdoctection/deepdoctection#320]
@JaMe76 
I am using colab when I try to make my pipeline and try to load layout-parser models but I don't know where should I load it. As it has no ".cache" directory. can you let me know if I create a folder and load weights and config files from that folder it will be handy. Can you share how to load?

**Comment by JaMe76** [comment]
Check this [tutorial](https://deepdoctection.readthedocs.io/en/latest/tutorials/running_pre_trained_models_from_third_party_libraries_notebook/). 
It shows you how to save your models manually in the .cache and how to add the model to the `ModelCatalog`.

**Comment by JaMe76** [comment]
To get the .cache you can find it like that

```
from deepdoctection.utils.settings import dd_cache_home

print(dd_cache_home)
```

You can also change the .cache dir by changing the env variable before setting everything else up: `DEEPDOCTECTION_CACHE`.
