### ISSUE TITLE
'deepdoctection.extern' has no attribute 'TPFrcnnDetector'

### ISSUE THREAD

**Issue by Alevik02** [deepdoctection/deepdoctection#322]
I'm following this tutorial: https://deepdoctection.readthedocs.io/en/latest/tutorials/layout_parsing_structure/ 
And the exact code from the tutorial gives me this error:
AttributeError: module 'deepdoctection.extern' has no attribute 'TPFrcnnDetector'

I should have everything installed.
Even the text editor I'm using shows me that the method exist, but when I try to run the error appears. 

Edit: I tried to import the method alone  from deepdoctection.extern and it gives me the error: 
ImportError: cannot import name 'TPFrcnnDetector' from 'deepdoctection.extern'

**Comment by JaMe76** [comment]
Can you check if you have both Tensorflow and Tensorpack installed ?

```
import deepdoctection as dd
from os import environ

print(dd.tensorpack_available())
dd.auto_select_lib_and_device()
print(environ.get("USE_TENSORFLOW"))
print(environ.get("USE_PYTORCH"))
print(environ.get("USE_CUDA"))
print(environ.get("USE_TF"))
print(environ.get("USE_TORCH"))
```
Anyway, along with #312, #285 and #306 it shows that something has to be done with the conditional imports. The current situation is not sustainable at all...

**Comment by Alevik02** [comment]
I only have Tensorflow installed

**Comment by JaMe76** [comment]
You need to install `Tensorpack` as well.

**Comment by Alevik02** [comment]
Thanks, after installing Tensorpack and upgrading the typing-extensions to 4.8 it seams to work properly.

**Comment by JaMe76** [comment]
> I guess 'cause of the typing-extensions upgrade, now some other stuff isn't working, should i make separate issue?

Yes, please. If it is something else, it's easier to work on if there is a separate issue.
