### ISSUE TITLE
I can't seem to solve both #322 and #323 at the same time

### ISSUE THREAD

**Issue by Alevik02** [deepdoctection/deepdoctection#325]
I encountered a problem trying to solve issue #322, if i install Tensorpack the problem (deepdoctecion.extern having no attribute named
TPFrcnnDetector) seems to go away, but at the same time the analyzer stops working (see issue #323).

The only way to make the analyzer work again is uninstalling Tensorpack, but that causes the first problem (issue #322)

**Comment by JaMe76** [comment]
I am not sure what you mean with “to make the analyzer work again” ? 
#322 is required because the TF models are wrapped with Offline-predictors based on Tensorpack.
Solving #323 requires to have a GPU available. 
Both issues are not exclusive.
