### ISSUE TITLE
Do you offer any commercial licenses or access to the full models for comprehensive testing?

### ISSUE THREAD

**Issue by chinmoybasak** [deepdoctection/deepdoctection#339]
Expected behavior 🧮
Describe what you would have expected

Question Regarding Full Version ❓
**I noticed that the models for layout detection and table recognition in deepdoctection are not open-sourced, and the OCR uses AWS Textract, a commercial service. Given this limitation, how can we test the full version of deepdoctection with the fully trained models? Do you offer any commercial licenses or access to the full models for comprehensive testing?**

Screenshots 🖼
If possible, please add a screenshot of the error message, if possible

Desktop (please complete the following information, if any other than the one in the install requirements):

Additional context 🧬
If necessary, add some context related to the problem

**Comment by JaMe76** [comment]
For everything that goes beyond Open Source, feel free to reach me [here](https://www.linkedin.com/in/dr-janis-meyer/).
