### ISSUE TITLE
Way to skip elements (process nonsequentially) in a data flow?

### ISSUE THREAD

**Issue by conjuncts** [deepdoctection/deepdoctection#343]
**Enhancement** 🚀
This is not really an enhancement, but more a question: is there a way to process dataflows non-sequentially? I tried looking through the documentation, searching online, even looking through the source code in deepdoctection/dataflow/common.py. From what I've seen, dataflow only implements the __iter__ methods. 

**Motivation**  💪 
I could wait for the iterator, but can that may take minutes at a time.

**Alternatives** ⚖️
I also tried
```
df = analyzer.analyze(path=path)
y = df[100]
```
but it didn't work.

**Additional context** 🧬

**Comment by JaMe76** [comment]
Right now, none of the dataflow classes have a `__getitem__` - method and I think it will only make sense for those that have a 1:1 correspondence between input and output (e.g. `SerializerFiles.load` and a few others but not for those that buffer datapoints and process inputs across several threads/processes or that take and one input and yield n outputs).

As long a the analyzer processes pages in a strict sequential manner it could be implemented, though.
