### ISSUE TITLE
Error in reproducing "analyzer_with_table_transformer_notebook.md"

### ISSUE THREAD

**Issue by greydanus** [deepdoctection/deepdoctection#344]
**Bug** 💥

The second cell of the notebook is crashing when it attempts to load model weights. It appears to be calling a PyTorch method on a model which, in the debugger, I found to have TensorFlow variables. Reproduce in Colab here: [https://colab.research.google.com/drive/1QK4N4xwoX3FkEPqjXPdbyC68uGjAo3Wy?usp=sharing](https://colab.research.google.com/drive/1QK4N4xwoX3FkEPqjXPdbyC68uGjAo3Wy?usp=sharing)

**Screenshots** 🖼
<img width="1185" alt="Screen Shot 2024-06-13 at 1 20 34 PM" src="https://github.com/deepdoctection/deepdoctection/assets/18602382/15e1841a-9860-4603-815c-6cd02515c079">

**Environment:**

Google Colaboratory

**Comment by JaMe76** [comment]
Many thanks! 

There is actually a bug when setting the priority env variables USE_TF, USE_TORCH if both Tensorflow and Torch are installed.

**Comment by greydanus** [comment]
You're welcome! How can I avoid this bug in the short term? I tried setting those env variables as shown here:

<img width="343" alt="Screen Shot 2024-06-14 at 7 42 15 AM" src="https://github.com/deepdoctection/deepdoctection/assets/18602382/ee2d3a78-42d3-43c4-9f47-f04549a2791d">

The Colab is updated to include that attempted, but unsuccessful fix -
[https://colab.research.google.com/drive/1QK4N4xwoX3FkEPqjXPdbyC68uGjAo3Wy#scrollTo=cZ43sflbQ7m7](https://colab.research.google.com/drive/1QK4N4xwoX3FkEPqjXPdbyC68uGjAo3Wy#scrollTo=cZ43sflbQ7m7)

**Comment by greydanus** [comment]
Ok, thanks for the response. I was able to fix this bug by adding:

```
os.environ["DD_USE_TORCH"] = "1"
os.environ["DD_USE_TF"]="0"
os.environ["USE_TORCH"] = "1"
os.environ["USE_TF"] = "0"
```

Before the line where I import deepdoctection (`import deepdoctection as dd`)

**Comment by JaMe76** [comment]
I have provided a fix so that PyTorch is the default library even if Tensorflow is also installed. It should be equivalent to your variable configuration.

You can find the fix on the master branch. It has not been added to a new release yet.

**Comment by greydanus** [comment]
I just pip installed from the master branch and the fix you describe solved my issue. Thanks for the quick fix!

**Comment by JaMe76** [comment]
Closing with https://github.com/deepdoctection/deepdoctection/commit/bfa642e302b069ca2aae8cc67cad8e4c0e20016b.
