### ISSUE TITLE
How to use LayoutLMv3 as just a layout detection model?

### ISSUE THREAD

**Issue by mohit-raghavendra** [deepdoctection/deepdoctection#362]
I am trying to replace the _detectron_ or _table-transformer_ models for **layout detection** with _LayoutLMv3_, but based on what I understand, LayoutLMv3 is only implemented for Sequence and Token Classification in deepdoctection. 

To initialize the Sequence classifier, I need to supply categories, which are not implemented for LayoutLMv3. So how do I use it? 

Basically, this works

```python
    layout_detector = dd.HFDetrDerivedDetector(path_config_json=path_config_json,
                                               path_weights=path_weights,
                                               categories=categories,
                                               path_feature_extractor_config_json=path_feature_extractor_config_json,
                                               device="cuda")
```

whereas this doesn't

```python
    layout_detector = dd.HFLayoutLmv3SequenceClassifier(path_config_json=path_config_json,
                                                        path_weights=path_weights,
                                                        categories=None,
                                                        device="cuda")

```

**Comment by JaMe76** [comment]
The Transformers library does not support LayoutLMv3 for object detection and because we do not implement any models and only provide wrappers there is no easy way to use LayoutLMv3 for object detection. 

I can only see you to implement a wrapper using the original MS unilm library and use their solutions directly.
