### ISSUE TITLE
cannot import name 'cached_download' from 'huggingface_hub' 

### ISSUE THREAD

**Issue by littlebuddha16** [deepdoctection/deepdoctection#373]
**Bug** 💥
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/Users/littlebuddha/Documents/GitHub/pdf_two_table/deepdoc/lib/python3.9/site-packages/huggingface_hub/__init__.py)"
}

**Expected behavior**  🧮 
Download the required models 
```
analyzer = dd.get_dd_analyzer()
```

**Screenshots** 🖼
If possible, please add a screenshot of the error message, if possible

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: macOS (Apple Silicon)

**Additional context** 🧬
{
	"name": "ImportError",
	"message": "cannot import name 'cached_download' from 'huggingface_hub' (/Users/littlebuddha/Documents/GitHub/pdf_two_table/deepdoc/lib/python3.9/site-packages/huggingface_hub/__init__.py)",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[5], line 1
----> 1 analyzer = dd.get_dd_analyzer()

File ~/Documents/GitHub/pdf_two_table/deepdoc/lib/python3.9/site-packages/deepdoctection/utils/file_utils.py:699, in _LazyModule.__getattr__(self, name)
    697     value = self._get_module(name)
    698 elif name in self._class_to_module.keys():  # pylint: disable=C0201
--> 699     module = self._get_module(self._class_to_module[name])
    700     value = getattr(module, name)
    701 else:

File ~/Documents/GitHub/pdf_two_table/deepdoc/lib/python3.9/site-packages/deepdoctection/utils/file_utils.py:709, in _LazyModule._get_module(self, module_name)
    707 @no_type_check
    708 def _get_module(self, module_name: str):
--> 709     return importlib.import_module(\".\" + module_name, self.__name__)

File /opt/homebrew/Cellar/python@3.9/3.9.19_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1030, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1007, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:986, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:680, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:850, in exec_module(self, module)

File <frozen importlib._bootstrap>:228, in _call_with_frames_removed(f, *args, **kwds)

File ~/Documents/GitHub/pdf_two_table/deepdoc/lib/python3.9/site-packages/deepdoctection/analyzer/__init__.py:22
      1 # -*- coding: utf-8 -*-
      2 # File: __init__.py
      3 
   (...)
     15 # See the License for the specific language governing permissions and
     16 # limitations under the License.
     18 \"\"\"
     19 Package for pre-built pipelines
     20 \"\"\"
---> 22 from .dd import *

File ~/Documents/GitHub/pdf_two_table/deepdoc/lib/python3.9/site-packages/deepdoctection/analyzer/dd.py:34
     30 from typing import Optional, Union
     32 from lazy_imports import try_import
---> 34 from ..extern.base import ObjectDetector
     35 from ..extern.d2detect import D2FrcnnDetector, D2FrcnnTracingDetector
     36 from ..extern.doctrocr import DoctrTextlineDetector, DoctrTextRecognizer

File ~/Documents/GitHub/pdf_two_table/deepdoc/lib/python3.9/site-packages/deepdoctection/extern/__init__.py:29
     27 from .hfdetr import *
     28 from .hflayoutlm import *
---> 29 from .model import *
     30 from .pdftext import *
     31 from .tessocr import *

File ~/Documents/GitHub/pdf_two_table/deepdoc/lib/python3.9/site-packages/deepdoctection/extern/model.py:27
     24 from typing import Any, Mapping, Optional, Union
     26 import jsonlines
---> 27 from huggingface_hub import cached_download, hf_hub_url  # type: ignore
     28 from tabulate import tabulate
     29 from termcolor import colored

ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/Users/littlebuddha/Documents/GitHub/pdf_two_table/deepdoc/lib/python3.9/site-packages/huggingface_hub/__init__.py)"
}

**Comment by JaMe76** [comment]
Thanks! 

The reason for this issue is that `huggingface_hub` 's compatible release isn't up to date anymore. I have already fixed this on `master` but when using `pip` you need to downgrade to `huggingface_hub>=0.12.0,<0.26`. A proper fix on PyPi will come into effect with `v.0.35.0`.

**Comment by JaMe76** [comment]
Closing with https://github.com/deepdoctection/deepdoctection/commit/ceca33c6b8d4ded44d307095e210180374028aed.
