### ISSUE TITLE
Issue raised while using Analyzer 

### ISSUE THREAD

**Issue by bhavansika** [deepdoctection/deepdoctection#39]
[JoinData] Size check failed for the list of dataflow to be joined!
Can you suggest the reason for this issue ASAP.

**Comment by JaMe76** [comment]
Hi, 

it is not easy to cause the root based on the information. 

Regarding the Analyzer JoinDataflow will be used in 

dataflow.custom_serialize.SerializerFiles

when loading files from a given file system. It iterates over os.walk in twice to get base directories and files. For some reason, this seem to break. 

I suggest to load less files from a subdirectory or to simplify the base directory structure.

**Comment by JaMe76** [comment]
Feel free to re-open this issue, if there is anything you are in doubt.

**Comment by AlokRaj1994** [comment]
I am facing the same issue.

Steps followed


#1 Cloned the full repository to google colab.
#2  Started Get_started.ipynb
#3  Executed block

path = "/content/deepdoctection/notebooks/pics/samples/sample_2"
df = analyzer.analyze(path=path)

Output [0713 11:29:21 @common.py:558] [JoinData] Size check failed for the list of dataflow to be joined!
|          |2/?[00:00<00:00,4403.47it/s]

I have'nt made any changes to the files / resources, but still getting the error.  
Attaching the file for your reference
Thank you
[Get_Started.zip](https://github.com/deepdoctection/deepdoctection/files/9108466/Get_Started.zip)

**Comment by JaMe76** [comment]
Thank you for pointing to this.

This one is new to me. I will have a closer look into this. However, this might take some time.

**Comment by JaMe76** [comment]
As far, as I can see, this is only an info message but not an error. At this stage there is no image processing at all and only the pipeline will be established. 

Image will be processed and models will be invoked once you run 

'''
doc=iter(df)
page = next(doc)
'''

in one of the following cells.

Can you please confirm that running the next cells of the notebook is still possible? 

I will see if I can silence this message in the following releases.

**Comment by JaMe76** [comment]
When looking at your notebook you attached, I can see that 

path = "/content/deepdoctection/notebooks/pics/samples/sample_2"
df = analyzer.analyze(path=path)

has been activated at step [9], whereas 

doc=iter(df)
page = next(doc)

has been activated at step [2]. There must have been something about running the notebook not in the right order. As already mentioned 

Size check failed for the list of dataflow to be joined! is only Info not error. This will return df.

I would re-instantiate the colas and re-run the notebook ensuring that all cells run in correct order.

**Comment by JaMe76** [comment]
Closed due to inactivity
