### ISSUE TITLE
Error while fine tuning

### ISSUE THREAD

**Issue by AlokRaj1994** [deepdoctection/deepdoctection#40]
ValueError: Invalid argument to SmartInit: /home/alokraj/.cache/deepdoctection/weights/cell/model-1800000.data-00000-of-00001
This error occurred while running the fine-tuning notebook's last cell

**Comment by JaMe76** [comment]
Thanks for the report. 

The notebook likely needs another step, namely downloading the checkpoint from the HF hub. I assume the artefact does not exist in your local cache.

You can download all registered models using the ModelDownloadManager, i.e.

```
ModelDownloadManager.maybe_download_weights_and_configs(“cell/model-1800000.data-00000-of-00001”)
```

TF Model for resuming training must be downloaded separately as they are much larger in size and contain many other checkpoint variables. On the other hand, if you have already used the analyzer from earlier notebooks, you maybe have inference only artefacts in your model cache (files like model-800000_inf_only.data-00000-of-00001). 

To see what models are available you can use the ModelCatalog:

```
print(ModelCatalog.get_model_list())
```

Let me know if this resolves the issue.

**Comment by AlokRaj1994** [comment]
So can we use model-800000_inf_only.data-00000-of-00001?

**Comment by JaMe76** [comment]
Not for fine tuning, e.g. running the notebook. You will need to download model-1800000.data-00000-of-0000. 
Models with inf_only suffix are only for inference.

**Comment by AlokRaj1994** [comment]
Can we import ModelDownloadManager

**Comment by JaMe76** [comment]
from deepdoctection.extern import ModelDownloadManager

**Comment by AlokRaj1994** [comment]
ok thanks for the reply

**Comment by AlokRaj1994** [comment]
Can we run this in google Colab?

**Comment by JaMe76** [comment]
I never tried. Might be possible, provided the GPU is decent (at least 6-8 GB RAM). File storage must be at least 18 GB as dataset is quite large. Don't know if Colab satisfies all requirements.

**Comment by AlokRaj1994** [comment]
Is GPU GTX 1050ti enough for training?

**Comment by JaMe76** [comment]
Sorry, don't know

**Comment by AlokRaj1994** [comment]
How can we add a new dataset to the the existing list of dataset?

**Comment by JaMe76** [comment]
Would you mind adding this question to the discussion section ? I am then happy to prepare an answer.  

This will make topic search easier for other user who might have the same question. 

Thank you!

**Comment by AlokRaj1994** [comment]
yes

**Comment by AlokRaj1994** [comment]
Added to discussion

**Comment by AlokRaj1994** [comment]
After the fine tuning from where can we get the new model?

**Comment by JaMe76** [comment]
From the log_dir you specified in the notebook. You can either use a relative from where you run the notebook or an absolute path. Tensorboard loggings, intermediate checkpoints will all be saved there.

**Comment by AlokRaj1994** [comment]
graph-0802-143741.meta
log.log
These are the files generated

**Comment by JaMe76** [comment]
Sounds that user does not have rights to save to this directory. 
.meta file is never UTF-8 encoded. 

I suggest you must grant rights in order to save something in log dir.

**Comment by AlokRaj1994** [comment]
ok thank you

**Comment by AlokRaj1994** [comment]
class CustomDataset(DatasetBase):

    @classmethod
    def _info(cls):
        return DatasetInfo(name=_NAME, description=_DESCRIPTION, splits=_SPLITS)

    def _categories(self):
        return DatasetCategories(init_categories=_CATEGORIES)

    def _builder(self):
        return CustomDataFlowBuilder(location=_LOCATION,annotation_files=_ANNOTATION_FILES)


when i run this

NameError: name 'DatasetBase' is not defined

should i do something before this?
NameError: name 'DatasetBase' is not defined

**Comment by JaMe76** [comment]
```
import deepdoctection as dd

class CustomDataset(dd.DatasetBase):

@classmethod
def _info(cls):
    return dd.DatasetInfo(name=_NAME, description=_DESCRIPTION, splits=_SPLITS)

def _categories(self):
    return dd.DatasetCategories(init_categories=_CATEGORIES)

def _builder(self):
    return CustomDataFlowBuilder(location=_LOCATION,annotation_files=_ANNOTATION_FILES)
```

You will have to write  `CustomDataFlowBuilder` by yourself as sub class of `DataFlowBaseBuilder` .

**Comment by AlokRaj1994** [comment]
ok thank you

**Comment by AlokRaj1994** [comment]
Should i create a customdataset.py file in datasets/instances?
