### ISSUE TITLE
[error] error when running with TensorFlow or PyTorch

### ISSUE THREAD

**Issue by ekopoerwanto** [deepdoctection/deepdoctection#60]
I'm follow step by step instruction installation from source. I try use TensorFlow and PyTorch, with Python 3.8.13 and Python 3.9.13

when all done, i try for running Get_Started.ipynb in folder /deepdoctection/notebooks/.. i get some error.. path for cairo not found

thank you for the support

**Comment by JaMe76** [comment]
Hi,

Cairo is a component of Poppler which is used to convert PDFs into numpy arrays. It does not ship with Python. 

Would you mind to check if all **Other** dependencies in the **Requirements** section of the README have been installed as well? Depending on your machine you must ensure that the command `pdftocairo` can be invoked.

**Comment by ekopoerwanto** [comment]
Hi,

Thank you Dr Janis Meyer. If I have a problem, I will ask

**Comment by ekopoerwanto** [comment]
i get this error :)

Thank you

TypeError                                 Traceback (most recent call last)
Cell In [16], line 5
      3 plt.figure(figsize = (25,17))
      4 plt.axis('off')
----> 5 plt.imshow(image)

File ~/Machine Learning/deep-learning/lib/python3.8/site-packages/matplotlib/pyplot.py:2903, in imshow(X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, filternorm, filterrad, resample, url, data, **kwargs)
   2897 @_copy_docstring_and_deprecators(Axes.imshow)
   2898 def imshow(
   2899         X, cmap=None, norm=None, aspect=None, interpolation=None,
   2900         alpha=None, vmin=None, vmax=None, origin=None, extent=None, *,
   2901         filternorm=True, filterrad=4.0, resample=None, url=None,
   2902         data=None, **kwargs):
-> 2903     __ret = gca().imshow(
   2904         X, cmap=cmap, norm=norm, aspect=aspect,
   2905         interpolation=interpolation, alpha=alpha, vmin=vmin,
   2906         vmax=vmax, origin=origin, extent=extent,
   2907         filternorm=filternorm, filterrad=filterrad, resample=resample,
   2908         url=url, **({"data": data} if data is not None else {}),
   2909         **kwargs)
   2910     sci(__ret)
   2911     return __ret

File ~/Machine Learning/deep-learning/lib/python3.8/site-packages/matplotlib/__init__.py:1361, in _preprocess_data.<locals>.inner(ax, data, *args, **kwargs)
   1358 @functools.wraps(func)
   1359 def inner(ax, *args, data=None, **kwargs):
   1360     if data is None:
-> 1361         return func(ax, *map(sanitize_sequence, args), **kwargs)
   1363     bound = new_sig.bind(ax, *args, **kwargs)
   1364     auto_label = (bound.arguments.get(label_namer)
   1365                   or bound.kwargs.get(label_namer))

File ~/Machine Learning/deep-learning/lib/python3.8/site-packages/matplotlib/axes/_axes.py:5609, in Axes.imshow(self, X, cmap, norm, aspect, interpolation, alpha, vmin, vmax, origin, extent, filternorm, filterrad, resample, url, **kwargs)
   5604 self.set_aspect(aspect)
   5605 im = mimage.AxesImage(self, cmap, norm, interpolation, origin, extent,
   5606                       filternorm=filternorm, filterrad=filterrad,
   5607                       resample=resample, **kwargs)
-> 5609 im.set_data(X)
   5610 im.set_alpha(alpha)
   5611 if im.get_clip_path() is None:
   5612     # image does not already have clipping set, clip to axes patch

File ~/Machine Learning/deep-learning/lib/python3.8/site-packages/matplotlib/image.py:700, in _ImageBase.set_data(self, A)
    696 self._A = cbook.safe_masked_invalid(A, copy=True)
    698 if (self._A.dtype != np.uint8 and
    699         not np.can_cast(self._A.dtype, float, "same_kind")):
--> 700     raise TypeError("Image data of dtype {} cannot be converted to "
    701                     "float".format(self._A.dtype))
    703 if self._A.ndim == 3 and self._A.shape[-1] == 1:
    704     # If just one dimension assume scalar and apply colormap
    705     self._A = self._A[:, :, 0]

TypeError: Image data of dtype object cannot be converted to float

**Comment by JaMe76** [comment]
I have uploaded a new version of Get_started notebook. It wouldn't have worked without the fix. 

However, I am not quite clear about, where you encountered there problem. `image` must be a `np.array` 
which obviously is not because of the type error. Moreover, some cells of the notebook have been run multiple times because the original notebook does not have 16 cells. Please make sure to run each cell in the right order.

**Comment by ekopoerwanto** [comment]
Yes, 

I'm done, follow your example  :).. please check this for results : https://github.com/ekopoerwanto/test

How about file pdf more than 1 (e.g 15 pdf files)

Thank you :)

**Comment by JaMe76** [comment]
A single pdf with multiple pages can be processed page by page using the `next` method.
Multiple pdf docs can be processed with a for loop.

**Comment by ekopoerwanto** [comment]
in final result (page.tables), if i want save to csv, can it?

because i check in your documentation :
save(path=None, save_image=False)
Save a page instance as .json

Thank you

**Comment by JaMe76** [comment]
Saving tables to csv is not supported yet. 

Main problem is: What do you with cell and row span/col span >1?

**Comment by ekopoerwanto** [comment]
in this my file https://github.com/ekopoerwanto/test/blob/master/1.ipynb, so i can't save my table ?

thank you :)

**Comment by JaMe76** [comment]
If you want to save something particularly, as raw text or table as html or .csv you will need to write something by yourself. There is only support for saving the whole page information as .json.

**Comment by ekopoerwanto** [comment]
for file path=path, this is must .pdf or another format?

because i try use .png, i get error code

Thank you

**Comment by JaMe76** [comment]
`path` must point either to a pdf doc or to a **folder** containing png, jpg, tif,…

**Comment by JaMe76** [comment]
Closed due to inactivity
