### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by dvivarelli** [deepdoctection/deepdoctection#79]
**Bug** 💥
On Colab, if I try to replicate the CustomPipeline notebook, after installing the dependencies i receive a NoModuleFoundError 

Dependencies:
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
!pip install deepdoctection[pt]

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-8-b0329ca60186>](https://localhost:8080/#) in <module>
      1 import os
----> 2 from deepdoctection.pipe import TextExtractionService, DoctectionPipe

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - Google Colab

**Comment by JaMe76** [comment]
It looks that the library has not been installed. 

Please check, if  
```
import deepdoctection
print(deepdoctection.__version__)
```

returns anything. I tried to follow your installation process: 

```
!pip install deepdoctection[pt]
```

will not install on a plain Colab workspace because of the pre-installed Python 3.7. 

However, the setup requires Python 3.8.

**Comment by dvivarelli** [comment]
you are right, colab is not supported. 
It works well on local installation.

Thanks
