### ISSUE TITLE
View.py save function does not return the dictionary

### ISSUE THREAD

**Issue by teuntjebrainial** [deepdoctection/deepdoctection#91]
**Bug** 💥
When putting the 'dry' parameter to True the function save returns None, however, the docstring states that it will return the dictionary without saving anything.

**Expected behavior**  🧮 
I expected the dictionary to be returned instead of None

**Screenshots** 🖼
![image](https://user-images.githubusercontent.com/98813080/204544123-51837ae4-9b4b-443d-b254-63f007b4385e.png)

this solves the issue:
![image](https://user-images.githubusercontent.com/98813080/204544257-2e47d1cc-3455-4c58-8fca-ecb8c151e8bb.png)

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Ubuntu 22.04

**Additional context** 🧬
If necessary add some context related to the problem

**Comment by JaMe76** [comment]
Thank you for pointing to the issue. 

Will be fixed following your suggestion.

**Comment by JaMe76** [comment]
Closing with PR #93
