### ISSUE TITLE
Anaconda Enviroment TesseractNotFound

### ISSUE THREAD

**Issue by LightAllWorld** [deepdoctection/deepdoctection#92]
**Bug** 💥
I went use deedoctection in Anaconda enviroment. So,  I downloaded Tesseract used to following command.

`$ conda install tesseract`

I followed tutorial python script about deepdoctection, and got `Tessearact NotFound Error`

-----

**Screenshots** 🖼
Here is my code.
![image](https://user-images.githubusercontent.com/26130839/204733289-6db3c890-7502-4a2b-b534-75ab4722b212.png)

Tesseract command in dia conda enviroment.
![image](https://user-images.githubusercontent.com/26130839/204732506-22502139-c7ee-4c1a-80f9-452af9c54531.png)

Error message
![image](https://user-images.githubusercontent.com/26130839/204732312-871c85db-17c8-4ae3-bf05-7168df330925.png)

------

**Desktop (please complete the following information, if any other than the one in the install requirements):**
 - OS: Ubuntu 20.04
- Python: 3.8.15
- Editor: Jupyter Notebook

**Additional context** 🧬
If necessary add some context related to the problem

**Comment by JaMe76** [comment]
Hi,

try

```python

import deepdoctection as dd

print(dd.tesseract_available())
print(dd.get_tesseract_version())
```

If you get `False` or an error or `0` then Tessearact has not been installed so that it can be accessed via subprocesses and I would check the installation process with conda again. Have you set env variables correctly?

**Comment by LightAllWorld** [comment]
Here is result.

![image](https://user-images.githubusercontent.com/26130839/204760703-0532d876-8dbf-4199-8a61-3732c0a9193e.png)

yes i have set conda env variables correctly.

I think subprocess running in my local, not conda env.
Could you please tell me how to set it up to run subprocess in my conda env?

**Comment by JaMe76** [comment]
Unfortunately, I don't know much about Anaconda but as you get 

```python
print(dd.tesseract_available())
False
```

I am pretty sure that Tesseract environ variables are not set. You can cross-check

```
from shutil import which
print("tesseract")
```
and if it returns `None` I suggest to search for environment variables and Tesseract. You will find a lot of help.

**Comment by LightAllWorld** [comment]
Ok I will try. If I solve this issue, I will share it.

Thx JaMe76

**Comment by LightAllWorld** [comment]
Hi, @JaMe76 

I solved this prob.

Pytesseract uses the default tesseract from localhost. So I solved it by overwriting my tesseract location.
The following code changes the tesseract location used by pytesseract.
```
import pytesseract as pt

pt.pytesseract.tesseract_cmd = <tesseract path>
```

If you faced "TESSDATA_PREFIX environment variable is set to your "tessdata" directory." error, you have to run following command.
```
$ export TESSDATA_PREFIX="<anaconda path>/envs/<env name>/share/tessdata/"
```
